force-app/main/default/objects/MPContractTerminationRecords__c/MPContractTerminationRecords__c.object-meta.xml
<CustomObject>
    <label>FTC</label>
    <nameField>
        <displayFormat>FTC-{0000}</displayFormat>
        <label>FTC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractTerminationRecords__c/fields/MPOrder__c.field-meta.xml
<CustomField>
    <fullName>MPOrder__c</fullName>
    <label>Orden</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>FTC</relationshipLabel>
    <relationshipName>FTC</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPContractTerminationRecords__c/fields/MPRejectionReason__c.field-meta.xml
<CustomField>
    <fullName>MPRejectionReason__c</fullName>
    <label>Motivo de Rechazo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPContractTerminationRecords__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <label>Solicitada</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>Recibida</label>
            </value>
            <value>
                <fullName>Socialized</fullName>
                <label>Socializada</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <label>Aceptada</label>
            </value>
            <value>
                <fullName>RejectedByItems</fullName>
                <label>Rechazada por Items</label>
            </value>
            <value>
                <fullName>RejectedByExceptionAndOrSpecialConditionToApply</fullName>
                <label>Rechazada por Excepción y/o Condición Especial por Aplicar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/MPTerminationRecord__c.object-meta.xml
<CustomObject>
    <label>Elemento de Ficha de Término</label>
    <nameField>
        <displayFormat>EFT-{0000}</displayFormat>
        <label>Elemento de Ficha de Término</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elementos de Ficha de Término</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPTerminationRecord__c/fields/FTC__c.field-meta.xml
<CustomField>
    <fullName>FTC__c</fullName>
    <label>FTC</label>
    <referenceTo>MPContractTerminationRecords__c</referenceTo>
    <relationshipLabel>Elementos de Ficha de Término</relationshipLabel>
    <relationshipName>MPTerminationRecords</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPCategory__c.field-meta.xml
<CustomField>
    <fullName>MPCategory__c</fullName>
    <label>Categoría</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPDescription__c.field-meta.xml
<CustomField>
    <fullName>MPDescription__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPDocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentNumber__c</fullName>
    <label>Número de documento</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPItemValue__c.field-meta.xml
<CustomField>
    <fullName>MPItemValue__c</fullName>
    <label>Valor de artículo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Aprobado</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPSubcategory__c.field-meta.xml
<CustomField>
    <fullName>MPSubcategory__c</fullName>
    <label>Subcategoría</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPFTCPrincipal__c.field-meta.xml
<CustomField>
    <fullName>MPFTCPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FTC Principal</label>
    <referenceTo>MPContractTerminationRecords__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPRejectionReason__c.field-meta.xml
<CustomField>
    <fullName>MPRejectionReason__c</fullName>
    <label>Motivo de rechazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RejectedByExceptionAndOrSpecialCondition</fullName>
                <label>Rechazada por Excepción y/o Condición Especial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageTerminationItems_ctrl.cls
public class ManageTerminationItems_ctrl {    

    @AuraEnabled(cacheable=true)
    public static List<MPTerminationRecord__c> getTerminationRecord(String idFTC) {
        List<MPTerminationRecord__c> lstTerminationRecord = new List<MPTerminationRecord__c>();
        List<order> lstorder = [select id,MPFTCPrincipal__c from order where id =: idFTC];
        if(lstorder.size()>0 && lstorder[0].MPFTCPrincipal__c != null){
            lstTerminationRecord = [SELECT id,MPDocumentNumber__c,MPDescription__c,MPCategory__c,
            MPSubcategory__c,MPItemValue__c,MPStatus__c,FTC__r.MPRejectionReason__c 
            FROM MPTerminationRecord__c WHERE FTC__c =: lstorder[0].MPFTCPrincipal__c order by MPStatus__c desc];
        }
        return lstTerminationRecord;
    }

    @AuraEnabled
    public static List<MPTerminationRecord__c> saveInformationClass(List<MPTerminationRecord__c> lstRejectedRecords,String strRejectedReason,String idFTC) {
        System.debug('ManageTerminationItems_ctrl  saveInformationClass 1: '+lstRejectedRecords.size()  );
        List<MPTerminationRecord__c> lstTerminationRecord = new List<MPTerminationRecord__c>();
        List<MPTerminationRecord__c> lstTerminationRecordToUpdate = new List<MPTerminationRecord__c>();

        List<order> lstorder = [select id,MPFTCPrincipal__c from order where id =: idFTC];
        System.debug('ManageTerminationItems_ctrl  saveInformationClass 2: '+lstorder.size()  );
        if(lstorder.size()>0 && lstorder[0].MPFTCPrincipal__c != null){
            MPContractTerminationRecords__c objContractTerminationRecords = new MPContractTerminationRecords__c();
            objContractTerminationRecords.id = lstorder[0].MPFTCPrincipal__c;
            objContractTerminationRecords.MPRejectionReason__c = strRejectedReason;
            update objContractTerminationRecords;

            lstTerminationRecord = [SELECT id,MPDocumentNumber__c,MPDescription__c,MPCategory__c,
            MPSubcategory__c,MPItemValue__c,MPStatus__c,FTC__r.MPRejectionReason__c 
            FROM MPTerminationRecord__c WHERE FTC__c =: lstorder[0].MPFTCPrincipal__c order by MPStatus__c desc];

            System.debug('ManageTerminationItems_ctrl  saveInformationClass 3: '+lstTerminationRecord.size());

            map<id,MPTerminationRecord__c> mapRejectedRecords = new map<id,MPTerminationRecord__c>(lstRejectedRecords);
            for(MPTerminationRecord__c iTerminationRecord : lstTerminationRecord){
                System.debug('ManageTerminationItems_ctrl  saveInformationClass 4: '+mapRejectedRecords.containsKey(iTerminationRecord.id));
                if(!mapRejectedRecords.containsKey(iTerminationRecord.id) && iTerminationRecord.MPStatus__c == 'Rejected'){
                    iTerminationRecord.MPStatus__c = 'Approved';
                    lstTerminationRecordToUpdate.add(iTerminationRecord);
                }else if(mapRejectedRecords.containsKey(iTerminationRecord.id) && iTerminationRecord.MPStatus__c != 'Rejected'){
                    iTerminationRecord.MPStatus__c = 'Rejected';
                    lstTerminationRecordToUpdate.add(iTerminationRecord);
                }
            }
        }

        update lstTerminationRecordToUpdate;
        return lstTerminationRecord;
    }
}