force-app/main/default/objects/MPContractCondition__c/MPContractCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Contrato</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Condición de Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractCondition__c/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Contrato</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>ContractConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPIsDefault__c.field-meta.xml
<CustomField>
    <fullName>MPIsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPContractCondition__c.field-meta.xml
<CustomField>
    <fullName>MPContractCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condición de Contrato</label>
    <referenceTo>MPContractCondition__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPCCQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Contrato</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Locales</relationshipLabel>
    <relationshipName>Locales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPUsabilityStatus__c.field-meta.xml
<CustomField>
    <fullName>MPUsabilityStatus__c</fullName>
    <label>Estado de Usabilidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPUsabilityStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractDate__c</fullName>
    <label>Fecha de contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <inlineHelpText>La fecha de fin del contrato se calcula según el tipo de registro de la oportunidad:
Nuevo Ingreso: Se calcula sumando el plazo al inicio del contrato en meses o años, según el tipo de plazo.
Modificación/Renovación: La fecha se obtiene directamente de la integración &quot;Obtener Contrato 4.1&quot; al momento de crear la oportunidad.</inlineHelpText>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractStartDate__c</fullName>
    <description>Oportunidad Nuevo Ingreso: Fecha en la que el contrato se firma
Oportunidad Mod/Renov: Fecha de creación de la oportunidad Mod/Renov</description>
    <inlineHelpText>Fecha en la que el contrato se firma</inlineHelpText>
    <label>Fecha de inicio del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <label>Tipo de Contrato</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrendamiento</fullName>
            </value>
            <value>
                <fullName>Subarrrendamiento</fullName>
            </value>
            <value>
                <fullName>Usufructo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CalculateDefautConditions_inv.cls
public with sharing class CalculateDefautConditions_inv {
     
    @InvocableMethod(label='Create Default Quote Condition')
    public static void createDefaultQuoteCondition_invmth(List<id> lstQuoteId) {
        CalculateDefautConditions_inv.createDefaultQuoteCondition(lstQuoteId);
    }
    public static void createDefaultQuoteCondition(List<id> lstQuoteId){
        List<Quote> lstQuote = new List<Quote>();
        List<MPContractCondition__c> lstContractCondition = new List<MPContractCondition__c>();
        List<MPQuoteCondition__c> lstQuoteCondition = new List<MPQuoteCondition__c>();
        
        set<id> setContractTypeId = new set<id>();       
        
        lstQuote = [select id,mpstore__r.MPContractType__c,Opportunityid,Opportunity.MPContractStartDate__c,Opportunity.MPContractDate__c,Opportunity.MPContractEndDate__c from Quote where id in: lstQuoteId];
        for(Quote iQuote : lstQuote){            
            setContractTypeId.add(iQuote.mpstore__r.MPContractType__c);
        }        
        String strQueryFields = Utilities_cls.getQueryFields(Utilities_cls.getAllFields('MPContractCondition__c'));
        lstContractCondition = Database.query('Select '+strQueryFields+' From MPContractCondition__c where MPContractType__c in: setContractTypeId and MPIsDefault__c = true and MPUsabilityStatus__c = \'Use\'');
        
        for(Quote iQuote : lstQuote){
            for(MPContractCondition__c jContractCondition: lstContractCondition){
                if(iQuote.mpstore__r.MPContractType__c == jContractCondition.MPContractType__c){                                                            
                    lstQuoteCondition.add(CreateQuoteCondition_inv.createQuoteCondition(iQuote,jContractCondition));
                }
            }
        } 
        insert lstQuoteCondition;
    }
    

}