force-app/main/default/objects/MPContractCondition__c/MPContractCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Contrato</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Condición de Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractCondition__c/fields/MPAdjustmentType__c.field-meta.xml
<CustomField>
    <fullName>MPAdjustmentType__c</fullName>
    <label>Tipo de Ajuste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPAdjustmentTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPConditionClass__c.field-meta.xml
<CustomField>
    <fullName>MPConditionClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase de Condición</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ContractConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Contrato</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>ContractConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPSuggestedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ajuste Sugerido</label>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipName>MPAdjustmentConditionClasses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPSuggestedCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de Cálculo Sugerida</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Contrato</relationshipLabel>
    <relationshipName>ContractConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPApplyTimeScale__c.field-meta.xml
<CustomField>
    <fullName>MPApplyTimeScale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplica Escala de Tiempo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPApplyVolumeScale__c.field-meta.xml
<CustomField>
    <fullName>MPApplyVolumeScale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplica Escala de Volumen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPConditionClass__c.field-meta.xml
<CustomField>
    <fullName>MPConditionClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase de Condición</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>QuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPContractCondition__c.field-meta.xml
<CustomField>
    <fullName>MPContractCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condición de Contrato</label>
    <referenceTo>MPContractCondition__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPCCQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPEndDate__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIsModifiable__c.field-meta.xml
<CustomField>
    <fullName>MPIsModifiable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modificable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ajuste Negociado</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.MPAdjustmentType__c</field>
            <operation>equals</operation>
            <value>Estratégico</value>
        </filterItems>
        <filterItems>
            <field>MPAdjustment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ajuste Estratégico</value>
        </filterItems>
        <filterItems>
            <field>$Source.MPAdjustmentType__c</field>
            <operation>equals</operation>
            <value>Por Inflación</value>
        </filterItems>
        <filterItems>
            <field>MPAdjustment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ajuste por Inflación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPAdjustmentQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de Cálculo Negociada</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto (Negotiation Calculation Rule)</relationshipLabel>
    <relationshipName>QuoteConditions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedValue__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedValue__c</fullName>
    <label>Valor Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPQuote__c.field-meta.xml
<CustomField>
    <fullName>MPQuote__c</fullName>
    <label>Presupuesto</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>QuoteConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPStartDate__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPSuggestedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ajuste Sugerido</label>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPSuggestedAdjustmentQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPSuggestedCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de Cálculo Sugerida</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto (Suggested Calculation Rule)</relationshipLabel>
    <relationshipName>QuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPSuggestedValue__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedValue__c</fullName>
    <label>Valor Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Contrato</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Locales</relationshipLabel>
    <relationshipName>Locales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractDate__c</fullName>
    <label>Fecha de contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <inlineHelpText>La fecha de fin del contrato se calcula según el tipo de registro de la oportunidad:
Nuevo Ingreso: Se calcula sumando el plazo al inicio del contrato en meses o años, según el tipo de plazo.
Modificación/Renovación: La fecha se obtiene directamente de la integración &quot;Obtener Contrato 4.1&quot; al momento de crear la oportunidad.</inlineHelpText>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractStartDate__c</fullName>
    <description>Oportunidad Nuevo Ingreso: Fecha en la que el contrato se firma
Oportunidad Mod/Renov: Fecha de creación de la oportunidad Mod/Renov</description>
    <inlineHelpText>Fecha en la que el contrato se firma</inlineHelpText>
    <label>Fecha de inicio del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <label>Tipo de Contrato</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrendamiento</fullName>
            </value>
            <value>
                <fullName>Subarrrendamiento</fullName>
            </value>
            <value>
                <fullName>Usufructo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPNegotiatedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedAdjustment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca en true si cambia un ajuste negociado en las condiciones de presupuesto relacionadas al presupuesto sincronizado y si ese valor es diferente al Ajuste Sugerido.</description>
    <label>Ajuste Negociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPNegotiatedValue__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedValue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automáticamente se marca cuando el calor negociado de las condiciones del presupuesto sincronizado es diferente al valor sugerido y el código de la clase de condición no inicia con AM.</description>
    <label>Valor Negociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateQuoteCondition_inv.cls
global with sharing class CreateQuoteCondition_inv {
    global class FlowInputs{
    
        @InvocableVariable
        global  quote objQuote;
        
        @InvocableVariable
        global  MPContractCondition__c objContractCondition;
        
    }
    
     global class FlowOutputs{
        
        @InvocableVariable
        global MPQuoteCondition__c objQuoteCondition;
      
    }
    
    @InvocableMethod(label='Create Quote Condition')
    global static List<FlowOutputs> createQuoteCondition_InvMth(List<FlowInputs> lstFlowInputs) {
        List<FlowOutputs> lstRSFlowOutputs = new List<FlowOutputs>();
        
        List<MPQuoteCondition__c> lstQuoteCondition = new List<MPQuoteCondition__c>();
        for(FlowInputs iFlowInputs : lstFlowInputs){ 
            MPQuoteCondition__c objQuoteCondition = CreateQuoteCondition_inv.createQuoteCondition(iFlowInputs.objQuote,iFlowInputs.objContractCondition);
            lstQuoteCondition.add(objQuoteCondition);
            
            FlowOutputs rsFlowOutputs = new FlowOutputs();
            rsFlowOutputs.objQuoteCondition = objQuoteCondition;
            lstRSFlowOutputs.add(rsFlowOutputs);
        }        
        insert lstQuoteCondition;       
        return lstRSFlowOutputs;
        
    }
    
    global static MPQuoteCondition__c createQuoteCondition(Quote objQuote , MPContractCondition__c objContractCondition){  
        Quote Quote = [select id,mpstore__r.MPContractType__c,Opportunityid,Opportunity.MPContractStartDate__c,Opportunity.MPContractDate__c,Opportunity.MPContractEndDate__c from Quote where id =: objQuote.id];              
        MPQuoteCondition__c objQuoteCondition = new MPQuoteCondition__c();
        objQuoteCondition.MPQuote__c = objQuote.id;
        objQuoteCondition.MPContractCondition__c = objContractCondition.id;
        objQuoteCondition.MPConditionClass__c= objContractCondition.MPConditionClass__c;
        objQuoteCondition.MPAdjustmentType__c = objContractCondition.MPAdjustmentType__c;
        objQuoteCondition.MPSuggestedAdjustment__c = objContractCondition.MPSuggestedAdjustment__c;
        objQuoteCondition.MPNegotiatedAdjustment__c = objContractCondition.MPSuggestedAdjustment__c;
        objQuoteCondition.MPSuggestedCalculationRule__c = objContractCondition.MPSuggestedCalculationRule__c;
        objQuoteCondition.MPNegotiatedCalculationRule__c = objContractCondition.MPSuggestedCalculationRule__c;
        objQuoteCondition.MPSuggestedValue__c = objContractCondition.MPSuggestedValue__c;
        objQuoteCondition.MPNegotiatedValue__c = objContractCondition.MPSuggestedValue__c;
        objQuoteCondition.MPApplyTimeScale__c=objContractCondition.MPApplyTimeScale__c;
        objQuoteCondition.MPApplyVolumeScale__c=objContractCondition.MPApplyVolumeScale__c;
        objQuoteCondition.MPIsModifiable__c = objContractCondition.MPIsModifiable__c;
        objQuoteCondition.MPStartDate__c=Quote.Opportunity.MPContractStartDate__c;
        objQuoteCondition.MPEndDate__c=Quote.Opportunity.MPContractEndDate__c;
        return objQuoteCondition;
    }
}