force-app/main/default/objects/MPBusinessType__c/MPBusinessType__c.object-meta.xml
<CustomObject>
    <label>Tipo de Negocio</label>
    <nameField>
        <label>Business Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Negocio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo Lookup hacia el registro en el objeto MPIntegrationStatus__c el cual muestra un Log de las integraciones</description>
    <label>Detalle de la integración</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPQuoteCondition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPPricingApiStatus__c.field-meta.xml
<CustomField>
    <fullName>MPPricingApiStatus__c</fullName>
    <description>Estado de la Integración de Precios.</description>
    <inlineHelpText>Estado de la Integración de Precios.</inlineHelpText>
    <label>Estado API Precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPQuote__c.field-meta.xml
<CustomField>
    <fullName>MPQuote__c</fullName>
    <label>Presupuesto</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>QuoteConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPSuggestedValue__c.field-meta.xml
<CustomField>
    <fullName>MPSuggestedValue__c</fullName>
    <label>Valor Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPRentalObjectByStore__c/MPRentalObjectByStore__c.object-meta.xml
<CustomObject>
    <label>Objeto de Alquiler por Local</label>
    <nameField>
        <displayFormat>ROS-{000000}</displayFormat>
        <label>Rental Object By Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos de Alquiler por Local</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPRentalObjectByStore__c/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Objetos de Alquiler</relationshipLabel>
    <relationshipName>RentalObjectsByStore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPPricingApiStatus__c.field-meta.xml
<CustomField>
    <fullName>MPPricingApiStatus__c</fullName>
    <description>Estado de la integración de precios de un registro de Condiciones de presupuesto asociado el cual necesita el valor sugerido provendiente de una API de precios.</description>
    <inlineHelpText>Estado de la integración de precios de un registro de Condiciones de presupuesto asociado el cual necesita el valor sugerido provendiente de una API de precios.</inlineHelpText>
    <label>Estado API Precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PricingAPITest.cls
/**
 * @description Clase de test para cumplir cobertura de las clases utilizadas en el consumo de la API de precios
 * @group Proyecto MP
 * @author Juan Felipe Muriel
 * @since 05-08-2024 - Creación
 */
@isTest
private class PricingAPITest {

   @testSetup
   static void setup(){

        /**Crear pricebook (Condicion de contrato) */
        Pricebook2 contractType = Build.anPricebook2()
           .withName('Contrato Comercial Perú')
           .withMPPaymentCondition('MP12')
           .withMPIsProRataMethod(true)
           .withMPExternalCode('P101')
           .withIsActive(true)
           .withCurrencyIsoCode('PEN')
           .build();
        insert contractType;
        /**Fin pricebook (Condicion de contrato) */

        /**Crear tipos de negocio */
        MPBusinessType__c sector = Build.anMPSector()
           .withName('Burger Food')
           .withMPExternalCode('S-000001')
           .withMPCategory('Autoplaza')
           .withCurrencyIsoCode('PEN')
           .build();
        MPBusinessType__c businessUnit = Build.anMPBusinessUnit()
           .withName('Fast Food')
           .withMPExternalCode('B-000001')
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<MPBusinessType__c>{sector,businessUnit};
        /**Fin tipos de negocio */

        /**Crear cuentas */
        Account parentAcc = Build.anMPAccount()
           .withName('Parent Account')
           .withAccountCurrency('PEN')
           .build();
        insert parentAcc;

        Account brandAccount = Build.anBrandAccount()
           .withName('Brand Account 01')
           .withAccountCurrency('PEN')
           .withParentAccount(parentAcc)
           .withMPSector(sector)
           .build();
        Account mallAccount = Build.anMallAccount()
           .withName('Mall Account 01')
           .withAccountCurrency('PEN')
           .withMPExternalCode('PNO')
           .build();
        Account societyAccount = Build.anSocietyAccount()
           .withName('Society Account 01')
           .withAccountCurrency('PEN')
           .build();
        insert new List<Account>{brandAccount, mallAccount, societyAccount} ;
        /**Fin crear cuentas */

        /**Crear locales y Objetos de alquiler */
        MPStore__c store = Build.anLocal()
           .withName('Local 1001')
           .withMPMall(mallAccount)
           .withMPFootage(100)
           .withMPExternalCode('store-0001')
           .withMPCeBe('cebe-001')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        MPStore__c rentalObject1 = Build.anMPRentalObject()
           .withName('OA 1001')
           .withMPMall(mallAccount)
           .withMPFootage(30)
           .withMPExternalCode('OA1001EXID')
           .withMPCeBe('')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        MPStore__c rentalObject2 = Build.anMPRentalObject()
           .withName('OA 1002')
           .withMPMall(mallAccount)
           .withMPFootage(30)
           .withMPExternalCode('OA1002EXID')
           .withMPCeBe('')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        insert new List<MPStore__c>{store,rentalObject1,rentalObject2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Objeto de Alquiler por local */
        MPRentalObjectByStore__c rentalObjectByStore1 = Build.anMPRentalObjectByStore()
           .withMPRentalObject(rentalObject1)
           .withMPStore(store)
           .build();
        MPRentalObjectByStore__c rentalObjectByStore2 = Build.anMPRentalObjectByStore()
           .withMPRentalObject(rentalObject2)
           .withMPStore(store)
           .build();
        insert new List<MPRentalObjectByStore__c>{rentalObjectByStore1,rentalObjectByStore2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Oportunidad */
        Opportunity opportunity1 = Build.anOpportunity()
           .withName('opportunity1')
           .withStageName('Exploración')
           .withAccount(parentAcc)
           .withMPBrand(brandAccount)
           .withMPMall(mallAccount)
           .withCloseDate((System.now().date()))
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<Opportunity>{opportunity1};
        /**Fin Oportunidad */

        /**Crear Quote */
        Quote quote1 = Build.anQuote()
           .withName('quote1')
           .withOpportunity(opportunity1)
           .withMPStore(store)
           .withStatus('Draft')
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<Quote>{quote1};
        /**Fin Quote */

        /**Crear Quote Condition */
        MPQuoteCondition__c quoteCondition1 = Build.anQuoteCondition()
           .withMPQuote(quote1)
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<MPQuoteCondition__c>{quoteCondition1};
        /**Fin Quote Quote Condition */
   }

    @isTest
   static void testQuoteConditionUpdate() {

      Integer httpCode = 200;
      Decimal priceResponse = 0.24145688653950015;
      String responseData = '{"pricing": ' + String.valueOf(priceResponse) +',"message": [{"code": "X0002","description": "RentalObject no fue encontrado, calculo no considera pasillo"}]}';
      String quoteToTestName = 'quote1';
      String integrationName = 'MPPricingAPI';
      String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
      
      Map<String, String> headerMap = new Map<String, String>();
      
      /** Obtener condición de cotizacion a actualizar */
      MPQuoteCondition__c mpqc = [SELECT Id FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName Limit 1];
      
      /** Crear log de integracion */
      MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
           .withStatus(inProgress)
           .withParentId(mpqc.id)
           .withMPIntegrationName(integrationName)
           .build();
      insert newLog;

      Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
      PricingAPICallManager callManager = new PricingAPICallManager(mpqc,false,newLog);
                  
      Test.startTest();
      // Encolar y ejecutar el trabajo queueable
      Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
      Test.stopTest();

      // Obtener registro actualizado
      MPQuoteCondition__c updatedMpqc = [SELECT Id,MPSuggestedValue__c FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName LIMIT 1];
      System.debug(updatedMpqc);

      Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
      Assert.areEqual(priceResponse, updatedMpqc.MPSuggestedValue__c, 'El precio sugerido debe coincidir con el valor de la respuesta.');
   }

   @isTest
   static void testHandleErrorResponseFromService() {

      Integer httpCode = 500;
      String quoteToTestName = 'quote1';
      Map<String, String> headerMap = new Map<String, String>();
      String responseData = '{"message": "500 - Server error"}';
      String integrationName = 'MPPricingAPI';
      String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
            
      /** Obtener condición de cotizacion a actualizar */
      MPQuoteCondition__c mpqc = [SELECT Id FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName Limit 1];
      
      
      /** Crear log de integracion */
      MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
      .withStatus(inProgress)
      .withParentId(mpqc.id)
      .withMPIntegrationName(integrationName)
      .build();
      insert newLog;
      
      Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
      PricingAPICallManager callManager = new PricingAPICallManager(mpqc,false,newLog);

      Test.startTest();
      // Encolar y ejecutar el trabajo queueable
      Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
      Test.stopTest();

      // Obtener registro actualizado
      MPQuoteCondition__c updatedMpqc = [SELECT Id,MPSuggestedValue__c,MPPricingApiStatus__c  FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName LIMIT 1];
      System.debug(updatedMpqc);

      Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
      Assert.areEqual('Error', updatedMpqc.MPPricingApiStatus__c, 'El estado debe ser Error');
   }

   @isTest
   static void testHandleErrorResponseRetries() {
      Boolean retries = true;
      Integer httpCode = 500;
      String quoteToTestName = 'quote1';
      Map<String, String> headerMap = new Map<String, String>();
      String responseData = '{"message": "500 - Server error"}';
      String integrationName = 'MPPricingAPI';
      String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
            
      /** Obtener condición de cotizacion a actualizar */
      MPQuoteCondition__c mpqc = [SELECT Id FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName Limit 1];
      
      /** Crear log de integracion */
      MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
      .withStatus(inProgress)
      .withParentId(mpqc.id)
      .withMPIntegrationName(integrationName)
      .build();
      insert newLog;
      
      Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
      PricingAPICallManager callManager = new PricingAPICallManager(mpqc,retries,newLog);

      Test.startTest();
      // Encolar y ejecutar el trabajo queueable
      Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
      Test.stopTest();

      // Obtener registro actualizado
      MPQuoteCondition__c updatedMpqc = [SELECT Id,MPSuggestedValue__c,MPPricingApiStatus__c  FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName LIMIT 1];
      System.debug(updatedMpqc);

      Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
      Assert.areEqual('Error', updatedMpqc.MPPricingApiStatus__c, 'El estado debe ser Error');
   }

   // @isTest
   // static void testQuoteConditionValidateResponse() {
   //    /** Validar que no se debe procesar correctamente el llamado a la API si el precio sugerido es 0 */
   //    Integer httpCode = 200;
   //    Decimal priceResponse = 0;
   //    String responseData = '{"pricing": ' + String.valueOf(priceResponse) +',"message": [{"code": "X0002","description": "RentalObject no fue encontrado, calculo no considera pasillo"}]}';
   //    String quoteToTestName = 'quote1';
   //    String integrationName = 'MPPricingAPI';
   //    String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
      
   //    Map<String, String> headerMap = new Map<String, String>();
      
   //    /** Obtener condición de cotizacion a actualizar */
   //    MPQuoteCondition__c mpqc = [SELECT Id FROM MPQuoteCondition__c WHERE MPQuote__r.Name =: quoteToTestName Limit 1];
      
   //    /** Crear log de integracion */
   //    MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
   //         .withStatus(inProgress)
   //         .withParentId(mpqc.id)
   //         .withMPIntegrationName(integrationName)
   //         .build();
   //    insert newLog;

   //    Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
   //    PricingAPICallManager callManager = new PricingAPICallManager(mpqc,false,newLog);
                  
   //    Test.startTest();
   //    // Encolar y ejecutar el trabajo queueable
   //    Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
   //    Test.stopTest();

   //    // Obtener registro actualizado
   //    MPQuoteCondition__c updatedMpqc = [
   //       SELECT Id,MPSuggestedValue__c,MPIntegrationStatus__c, MPIntegrationStatus__r.MPSalesforceException__c, MPIntegrationStatus__r.MPStatus__c
   //       FROM MPQuoteCondition__c 
   //       WHERE MPQuote__r.Name =: quoteToTestName LIMIT 1];
   //    System.debug(updatedMpqc);
   //    System.debug(updatedMpqc.MPIntegrationStatus__r.MPSalesforceException__c);
   //    System.debug(updatedMpqc.MPIntegrationStatus__r.MPStatus__c);


   //    Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
   //    Assert.isNotNull(updatedMpqc.MPIntegrationStatus__c, 'El lookup de Integration status no debe ser null.');
   //    Assert.isNull(updatedMpqc.MPSuggestedValue__c, 'El precio sugerido debe ser null');
   // }
}