force-app/main/default/objects/Contract/fields/MPContractDatesUpdateStatus__c.field-meta.xml
<CustomField>
    <fullName>MPContractDatesUpdateStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles Api Actualización de Fechas</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractDatesUpdateAPI_Inv.cls
/**
 * @description Clase usada desde 'Screen Flows' para invocar la integración de actualización de fechas de contrato.
 * @group Proyecto MP
 * @author Juan Felipe Muriel
 * @since 26-08-2024 - Creación
 */
public with sharing class ContractDatesUpdateAPI_Inv {
    /** Estado inicial de la integración */
    private static final String IN_PROGRESS_STATUS = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
    /** Nombre de la integración */
    private static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').DeveloperName;
    /** Permitir o no hacer reintentos */
    public static final Boolean IS_RETRY_ENABLED = false;

    /**
     * @description Método encargado de ejecutar la integración de actualizacion de fechas de contratos.
     * @author Juan Felipe Muriel | 26-08-2024 
     * @param contractList Contratos a activar.
     */
    @InvocableMethod(label='Call the Contract Dates Update API' description='Call the Contract Dates Update API.' category='Contract')
    public static void contractDatesUpdateAPI(List<Contract> contractList) {

        Map<Id,MPIntegrationStatus__c> intStatusByContractIdMap = new Map<Id,MPIntegrationStatus__c>();
        List<Contract> contractsToUpdateList = new List<Contract>();

        // Recorrer todos los contratos y organizar mapa
        for(Contract contract : contractList){
            if(!intStatusByContractIdMap.containsKey(contract.Id)){
                MPIntegrationStatus__c newLog = getIntStatus(contract.Id);
                intStatusByContractIdMap.put(contract.Id, newLog);
            }
        }
        
        // Insertar logs de la integración (MPIntegrationStatus__c)
        if(!intStatusByContractIdMap.isEmpty()){
            insert intStatusByContractIdMap.values();
        }

        // asignar a los contratos la lupa al log de integraciones
        for(Contract contract : contractList){
            if(intStatusByContractIdMap.containsKey(contract.Id)){
                Contract contractTemp = new Contract(
                    id = contract.Id,
                    MPContractDatesUpdateStatus__c = intStatusByContractIdMap.get(contract.Id).Id
                );
                contractsToUpdateList.add(contractTemp);
            }
        }

        // Actualizar contratos
        if(!contractsToUpdateList.isEmpty()){
            update contractsToUpdateList;
        }

        // Recorrer contratos y encolar trabajos
        for(Contract contract : contractList ){
            if(intStatusByContractIdMap.containsKey(contract.Id) && !Test.isRunningTest()){
                ContractDatesUpdateAPICallManager callManager = new ContractDatesUpdateAPICallManager(contract,IS_RETRY_ENABLED,intStatusByContractIdMap.get(contract.Id));
                System.enqueueJob(new CallManagerQueueable(callManager));
            }
        }
    }

    /**
     * @description Método encargado de crear una nueva instancia del objeto 'MPIntegrationStatus__c'
     * @author Juan Felipe Muriel | 26-08-2024 
     * @param contractId Id de un contrato
     * @return Nueva instancia de 'MPIntegrationStatus__c'
     */
    private static MPIntegrationStatus__c getIntStatus(Id contractId) {
        MPIntegrationStatus__c newLog = new MPIntegrationStatus__c();
        newLog.MPIntegrationName__c    = INTEGRATION_NAME;
        newLog.MPParentId__c           = String.valueOf(contractId);
        newLog.MPStatus__c             = IN_PROGRESS_STATUS;
        return newLog;
    }
}