force-app/main/default/objects/Contract/fields/MPContractModificationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPContractModificationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles API Modificación de Contrato</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Contracts (Detalles API Modificación de Contrato)</relationshipLabel>
    <relationshipName>Contracts_MPContractModificationStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParams__c.field-meta.xml
<CustomField>
    <fullName>MPParams__c</fullName>
    <description>Parametros agregados al cuerpo de la solicitud</description>
    <label>Parámetros</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractModificationAPIUtils.cls
/**
 * @description       : 
 * @author            : Juan Felipe Muriel
 * @group             : 
 * @last modified on  : 29-08-2024
 * @last modified by  : Juan Felipe Muriel
**/
public with sharing class ContractModificationAPIUtils {
    /** Nombre de la integración */
    private static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPContractModification').DeveloperName;

    /**
    * @description Método el cual actualza el contrato con el Lookup de la integración
    * @author Juan Felipe Muriel | 05-08-2024 
    * @param contractId Id del contrato a actualizar
    * @param integrationStatusId Id del registro del log de la transacción
    **/
    public static void updateContract(Id contractId,  Id integrationStatusId){
        if(contractId != null && integrationStatusId != null){
            Contract contractToUpdate = new Contract(Id = contractId, MPContractModificationStatus__c = integrationStatusId );
            update contractToUpdate;
        }
    }

    /**
    * @description Método el cual modifica los valores del log de integracion antes de hacer UPDATE
    * @author Juan Felipe Muriel | 22-08-2024 
    * @param callManager Instancia del callManager
    **/
    public static MPIntegrationStatus__c modifyIntegrationLog(ContractModificationAPICallManager callManager){
        MPIntegrationStatus__c updatedIntStat  = callManager.getIntegrationStatus();
        updatedIntStat.MPIntegrationName__c    = INTEGRATION_NAME;
        updatedIntStat.MPParentId__c           = callManager.getContract() != null ? callManager.getContract().Id : null;
        updatedIntStat.MPStatus__c             = callManager.getContractWrapperSAP().status;
        updatedIntStat.MPRequest__c            = JSON.Serialize(callManager.getContractWrapperSAP().request);
        updatedIntStat.MPRequestDateTime__c    = callManager.getContractWrapperSAP().requestDateTime;
        updatedIntStat.MPResponse__c           = JSON.Serialize(callManager.getContractWrapperSAP().response);
        updatedIntStat.MPResponseDateTime__c   = callManager.getContractWrapperSAP().requestDateTime;
        updatedIntStat.MPParams__c             = JSON.serialize(callManager.getContractWrapperSAP().params);
        updatedIntStat.MPSalesforceException__c= callManager.getContractWrapperSAP().salesforceErrorMessage;
        updatedIntStat.MPHttpCode__c           = callManager.getContractWrapperSAP().httpCode;

        // Si la transacción está marcada como error, solo agregar en la respuesta el error de callOut
        if(callManager.getContractWrapperSAP().status != Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c')){
            updatedIntStat.MPResponse__c = callManager.getContractWrapperSAP().errorMessage != null ? callManager.getContractWrapperSAP().errorMessage : null;
        }else{
            updatedIntStat.MPResponse__c = callManager.getContractWrapperSAP().response != null ? JSON.serialize(callManager.getContractWrapperSAP().response) : null ;
        }
        return updatedIntStat;
    }
}