force-app/main/default/objects/Contract/fields/MPCurrentOrder__c.field-meta.xml
<CustomField>
    <fullName>MPCurrentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido Vigente</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPEndDate__c</fullName>
    <label>Fecha Fin de Contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPOpportunity__c.field-meta.xml
<CustomField>
    <fullName>MPOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indica que oportunidad generó el contrato</inlineHelpText>
    <label>Oportunidad de origen</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/MPAdjustment__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado que permite generar ajustes en las clases de condición reajustables de acuerdo al tipo de contrato al que pertenecen.</description>
    <label>Ajuste</label>
    <nameField>
        <label>Nombre Ajuste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ajustes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPAdjustment__c/fields/MPValue__c.field-meta.xml
<CustomField>
    <fullName>MPValue__c</fullName>
    <label>Valor</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/MPContractCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Contrato</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Condición de Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractCondition__c/fields/MPConditionClass__c.field-meta.xml
<CustomField>
    <fullName>MPConditionClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase de Condición</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ContractConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPExternalPurpose__c.field-meta.xml
<CustomField>
    <fullName>MPExternalPurpose__c</fullName>
    <label>Propósito Frente al Contrato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPContractCondition__c/fields/MPTimeFrequency__c.field-meta.xml
<CustomField>
    <fullName>MPTimeFrequency__c</fullName>
    <label>Frecuencia de Tiempo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/MPOrderCondition__c.object-meta.xml
<CustomObject>
    <label>Condiciones de Pedido</label>
    <nameField>
        <displayFormat>OC{00000}</displayFormat>
        <label>Order Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPOrderCondition__c/fields/MPCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de cálculo</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPConditionClass__c.field-meta.xml
<CustomField>
    <fullName>MPConditionClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase de Condición</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPEndDate__c</fullName>
    <label>Fecha fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPExternalPurpose__c.field-meta.xml
<CustomField>
    <fullName>MPExternalPurpose__c</fullName>
    <label>Propósito Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPFinalVolume__c.field-meta.xml
<CustomField>
    <fullName>MPFinalVolume__c</fullName>
    <label>Volumen final</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPInitialVolume__c.field-meta.xml
<CustomField>
    <fullName>MPInitialVolume__c</fullName>
    <label>Volumen inicial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPOrder__c.field-meta.xml
<CustomField>
    <fullName>MPOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPStartDate__c</fullName>
    <label>Fecha inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPTimeFrequency__c.field-meta.xml
<CustomField>
    <fullName>MPTimeFrequency__c</fullName>
    <label>Frecuencia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPValue__c.field-meta.xml
<CustomField>
    <fullName>MPValue__c</fullName>
    <label>Valor negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPApplyTimeScale__c.field-meta.xml
<CustomField>
    <fullName>MPApplyTimeScale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplica Escala de Tiempo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPApplyVolumeScale__c.field-meta.xml
<CustomField>
    <fullName>MPApplyVolumeScale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplica Escala de Volumen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPConditionClass__c.field-meta.xml
<CustomField>
    <fullName>MPConditionClass__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clase de Condición</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>QuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPContractCondition__c.field-meta.xml
<CustomField>
    <fullName>MPContractCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condición de Contrato</label>
    <referenceTo>MPContractCondition__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPCCQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPEndDate__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ajuste Negociado</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
        <filterItems>
            <field>$Source.MPAdjustmentType__c</field>
            <operation>equals</operation>
            <value>Estratégico</value>
        </filterItems>
        <filterItems>
            <field>MPAdjustment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ajuste Estratégico</value>
        </filterItems>
        <filterItems>
            <field>$Source.MPAdjustmentType__c</field>
            <operation>equals</operation>
            <value>Por Inflación</value>
        </filterItems>
        <filterItems>
            <field>MPAdjustment__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ajuste por Inflación</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPAdjustmentQuoteConditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de Cálculo Negociada</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto (Negotiation Calculation Rule)</relationshipLabel>
    <relationshipName>QuoteConditions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPNegotiatedValue__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedValue__c</fullName>
    <label>Valor Negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPQuote__c.field-meta.xml
<CustomField>
    <fullName>MPQuote__c</fullName>
    <label>Presupuesto</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>QuoteConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPStartDate__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPScale__c/MPScale__c.object-meta.xml
<CustomObject>
    <label>Escala</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Scale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPScale__c/fields/Escala__c.field-meta.xml
<CustomField>
    <fullName>Escala__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escala</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPScale__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Time</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPScale__c</referenceTo>
    <relationshipLabel>Escalas</relationshipLabel>
    <relationshipName>Escalas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPEndDate__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPFinalVolume__c.field-meta.xml
<CustomField>
    <fullName>MPFinalVolume__c</fullName>
    <label>Volumen Final</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPInitialVolume__c.field-meta.xml
<CustomField>
    <fullName>MPInitialVolume__c</fullName>
    <label>Volumen inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condición de Presupuesto</label>
    <referenceTo>MPQuoteCondition__c</referenceTo>
    <relationshipLabel>Escalas</relationshipLabel>
    <relationshipName>Escalas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPStartDate__c</fullName>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPScale__c/fields/MPValue__c.field-meta.xml
<CustomField>
    <fullName>MPValue__c</fullName>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPScale__c/recordTypes/Time.recordType-meta.xml
<RecordType>
    <fullName>Time</fullName>
    <active>true</active>
    <label>Time</label>
</RecordType>

force-app/main/default/objects/MPScale__c/recordTypes/Volume.recordType-meta.xml
<RecordType>
    <fullName>Volume</fullName>
    <active>true</active>
    <label>Volume</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/MPNegotiatedAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedAdjustment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca en true si cambia un ajuste negociado en las condiciones de presupuesto relacionadas al presupuesto sincronizado y si ese valor es diferente al Ajuste Sugerido.</description>
    <label>Ajuste Negociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPNegotiatedValue__c.field-meta.xml
<CustomField>
    <fullName>MPNegotiatedValue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automáticamente se marca cuando el calor negociado de las condiciones del presupuesto sincronizado es diferente al valor sugerido y el código de la clase de condición no inicia con AM.</description>
    <label>Valor Negociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/createOrderCondition_cls.cls
/**
 * @description Automatic creation of Order Condition when the contract is created
 * @group Proyecto MP
 * @author Marco Guevara (MG)
 * @since 29-08-2024 - Creación
 */
public class createOrderCondition_cls {
    /**
     * @description Invocable Method that call the cration of the order conditions
     * @author Marco Guevara | 29-08-2024 
     * @param lstContractId List of contract ids
     */
    @InvocableMethod(label='Call the Pricing API' description='Call the Pricing API in order to obtain the suggested value for the condition class' category='Quote Condition')
    public static void createOrderCondition(List<Id> lstContractId) {
        createOrderCondition_cls.transformQuoteCondition(lstContractId);
    }
    
    public static void transformQuoteCondition(List<ID> lstContractId){        
        map<id,MPQuoteCondition__C> mapQuoteCondition = new map<id,MPQuoteCondition__C>();
        
        List<Contract> lstContract = new List<Contract>();
        List<MPScale__c> lstScale = new List<MPScale__c>();
        List<MPOrderCondition__c> lstOrderCondition = new List<MPOrderCondition__c>();
        
        Set<id> setQuoteId = new Set<id>();
        
        lstContract = [select id,MPOpportunity__r.SyncedQuoteId,MPCurrentOrder__c from contract where id in: lstContractId];
        for(Contract iContract : lstContract){
            setQuoteId.add(iContract.MPOpportunity__r.SyncedQuoteId);
        }
        
        mapQuoteCondition = new map<id,MPQuoteCondition__C>([select id,MPContractCondition__r.MPExternalPurpose__c,MPStartDate__c,MPEndDate__c,MPContractCondition__r.MPTimeFrequency__c,MPNegotiatedValue__c,MPNegotiatedAdjustment__c,MPQuote__r.opportunityid,MPApplyTimeScale__c,MPApplyVolumeScale__c,MPConditionClass__c,MPNegotiatedCalculationRule__c from MPQuoteCondition__C where MPQuote__c in: setQuoteId ]);
        lstScale = [select id,MPQuoteCondition__c,recordtype.name,MPEndDate__c,MPStartDate__c,MPValue__c,MPFinalVolume__c,MPInitialVolume__c,Escala__c from MPScale__c where MPQuoteCondition__c in: mapQuoteCondition.keyset() or Escala__r.MPQuoteCondition__c in: mapQuoteCondition.keyset()];
        system.debug('createOrderCondition Scale Conunt: '+lstScale.size());
        system.debug('createOrderCondition Quote COndition Conunt: '+mapQuoteCondition.size());
        for(Contract iContract : lstContract){
            for(MPQuoteCondition__C jQuoteCondition : mapQuoteCondition.values()){
                if(jQuoteCondition.MPQuote__c == iContract.MPOpportunity__r.SyncedQuoteId){
                    Boolean blnWithouteRecord = true;
                    if(jQuoteCondition.MPApplyTimeScale__c || jQuoteCondition.MPApplyVolumeScale__c){
                        for(MPScale__c kScale : lstScale){
                            if(kScale.MPQuoteCondition__c == jQuoteCondition.id){    
                                
                                if(!jQuoteCondition.MPApplyTimeScale__c && jQuoteCondition.MPApplyVolumeScale__c){                                    
                                    blnWithouteRecord=false;
                                    //Case #1 The Quote Condition has volume scale but no time scale
                                    MPOrderCondition__c objOrderCondition = createOrderCondition_cls.getOrderCondition(iContract, jQuoteCondition);
                                    objOrderCondition.MPValue__c = kScale.MPValue__c;
                                    objOrderCondition.MPEndDate__c = jQuoteCondition.MPEndDate__c;
                                    objOrderCondition.MPStartDate__c=jQuoteCondition.MPStartDate__c;                                                                                                
                                    objOrderCondition.MPFinalVolume__c = kScale.MPFinalVolume__c;
                                    objOrderCondition.MPInitialVolume__c = kScale.MPInitialVolume__c;                                
                                    lstOrderCondition.add(objOrderCondition);
                                } else if(jQuoteCondition.MPApplyTimeScale__c){
                                    Boolean blnWithouteRecord2 = true;
                                    if(jQuoteCondition.MPApplyVolumeScale__c){
                                        for(MPScale__c nScale : lstScale){
                                            if(nScale.Escala__c == kScale.id){
                                                blnWithouteRecord=false;
                                                blnWithouteRecord2 = false;
                                                //Case #2 The Quote Condition has time scale and the time scale has Volume scale
                                                MPOrderCondition__c objOrderCondition = createOrderCondition_cls.getOrderCondition(iContract, jQuoteCondition);
                                                objOrderCondition.MPValue__c = kScale.MPValue__c;                                
                                                objOrderCondition.MPEndDate__c = kScale.MPEndDate__c;
                                                objOrderCondition.MPStartDate__c=kScale.MPStartDate__c;                                                                                                
                                                objOrderCondition.MPFinalVolume__c = nScale.MPFinalVolume__c;
                                                objOrderCondition.MPInitialVolume__c = nScale.MPInitialVolume__c;                                
                                                lstOrderCondition.add(objOrderCondition);
                                            }
                                        }
                                    }
                                    
                                    if(blnWithouteRecord2){
                                        blnWithouteRecord=false;
                                        //Case #3 The Quote Condition has time scale and the time scale has no Volume scale
                                        MPOrderCondition__c objOrderCondition = createOrderCondition_cls.getOrderCondition(iContract, jQuoteCondition);
                                        objOrderCondition.MPValue__c = kScale.MPValue__c;                                
                                        objOrderCondition.MPEndDate__c = kScale.MPEndDate__c;
                                        objOrderCondition.MPStartDate__c=kScale.MPStartDate__c;                                                                    
                                        lstOrderCondition.add(objOrderCondition);
                                    }
                                } 
                            }
                        }
                    }
                    
                    if(blnWithouteRecord){
                        //Case #4 The Quote Condition has no scales
                        MPOrderCondition__c objOrderCondition = createOrderCondition_cls.getOrderCondition(iContract, jQuoteCondition);
                        objOrderCondition.MPValue__c = jQuoteCondition.MPNegotiatedValue__c;
                        objOrderCondition.MPEndDate__c = jQuoteCondition.MPEndDate__c;
                        objOrderCondition.MPStartDate__c=jQuoteCondition.MPStartDate__c;                                                                     
                        lstOrderCondition.add(objOrderCondition);
                    }                    
                }                
            }
            
        }
        
        if(lstOrderCondition.size()>0)
            insert lstOrderCondition;
    }
    
    public static MPOrderCondition__c getOrderCondition(Contract objContract,MPQuoteCondition__C objQuoteCondition){
        MPOrderCondition__c objOrderCondition = new MPOrderCondition__c();
        objOrderCondition.MPOrder__c = objContract.MPCurrentOrder__c;
        objOrderCondition.MPConditionClass__c = objQuoteCondition.MPConditionClass__c;
        objOrderCondition.MPCalculationRule__c = objQuoteCondition.MPNegotiatedCalculationRule__c;
        objOrderCondition.MPAdjustment__c = objQuoteCondition.MPNegotiatedAdjustment__c;
        objOrderCondition.MPTimeFrequency__c = objQuoteCondition.MPContractCondition__r.MPTimeFrequency__c;
        objOrderCondition.MPExternalPurpose__c = objQuoteCondition.MPContractCondition__r.MPExternalPurpose__c;
        return objOrderCondition;
    }
    
}