force-app/main/default/objects/Contract/fields/MPCurrentOrder__c.field-meta.xml
<CustomField>
    <fullName>MPCurrentOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido Vigente</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <inlineHelpText>La fecha de fin del contrato se calcula según el tipo de registro de la oportunidad:
Nuevo Ingreso: Se calcula sumando el plazo al inicio del contrato en meses o años, según el tipo de plazo.
Modificación/Renovación: La fecha se obtiene directamente de la integración &quot;Obtener Contrato 4.1&quot; al momento de crear la oportunidad.</inlineHelpText>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractStartDate__c</fullName>
    <description>Oportunidad Nuevo Ingreso: Fecha en la que el contrato se firma
Oportunidad Mod/Renov: Fecha de creación de la oportunidad Mod/Renov</description>
    <inlineHelpText>Fecha en la que el contrato se firma</inlineHelpText>
    <label>Fecha de inicio del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractType__c.field-meta.xml
<CustomField>
    <fullName>MPContractType__c</fullName>
    <label>Tipo de Contrato</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Arrendamiento</fullName>
            </value>
            <value>
                <fullName>Subarrrendamiento</fullName>
            </value>
            <value>
                <fullName>Usufructo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPGetContract41API__c.field-meta.xml
<CustomField>
    <fullName>MPGetContract41API__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integración Get Contract 4.1</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MP_Local__c.field-meta.xml
<CustomField>
    <fullName>MP_Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractStartDate__c</fullName>
    <label>Fecha de inicio del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ModificationNewQuote_inv.cls
global with sharing class ModificationNewQuote_inv {
    
    
    @InvocableMethod(label='Calculate Quote Condition of Mod Opp')
    global static void createQuoteConditionModOpp_InvMth(List<id> lstQuoteId) {
        system.debug('*************** ModificationNewQuote_inv createQuoteConditionModOpp_InvMth: '+lstQuoteId.size());
        
        List<Opportunity> lstOpportunity = new List<Opportunity>();
        List<Quote> lstQuote = new List<Quote>();
        set<id> setOppId = new set<id>();
        lstQuote = [select id,opportunityid,Opportunity.MPContractStartDate__c,Opportunity.MPContractEndDate__c from quote where id in: lstQuoteId];
        
        for(Quote Quotei : lstQuote){ 
            setOppId.add(Quotei.opportunityid);
        }        
        lstOpportunity = [select id,MPGetContract41API__r.MPResponse__c,Contract.MPCurrentOrder__r.MP_Local__c,Contract.MPCurrentOrder__r.MP_Local__r.MPContractType__c from Opportunity where id in: setOppId];
        DefaultQuote_cls.getConditionsFromContract(lstOpportunity,lstQuote);
         
    }
    
}