force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/MPInvoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FCT-{00000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPInvoice__c/fields/MPCreatedAt__c.field-meta.xml
<CustomField>
    <fullName>MPCreatedAt__c</fullName>
    <label>Fecha de Creación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPDocumentId__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentId__c</fullName>
    <label>ID de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPDocumentType__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentType__c</fullName>
    <label>Tipo de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>MPGrossAmount__c</fullName>
    <label>Monto Bruto</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>MPInvoiceNumber__c</fullName>
    <label>Número de Factura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MPTermination</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPSociety__c.field-meta.xml
<CustomField>
    <fullName>MPSociety__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sociedad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sociedad</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locales (Sociedad)</relationshipLabel>
    <relationshipName>MPSocietyStores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MP_Local__c.field-meta.xml
<CustomField>
    <fullName>MP_Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPStage__c.field-meta.xml
<CustomField>
    <fullName>MPStage__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activación de Término</fullName>
            </value>
            <value>
                <fullName>Negociación</fullName>
            </value>
            <value>
                <fullName>Condición de Pago</fullName>
            </value>
            <value>
                <fullName>Deshabilitación</fullName>
            </value>
            <value>
                <fullName>Proceso Judicial</fullName>
            </value>
            <value>
                <fullName>Cerrado Ganado</fullName>
            </value>
            <value>
                <fullName>Cerrado Perdido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceCreateService.cls
/**
 * @description       : Servicio para manejar la lógica de negocio en la creación de facturas.
 * @author            : Luis Sandoval
 * @group             : 
 * @last modified on  : 31-10-2024
 * @last modified by  : Luis Sandoval
**/
public with sharing class InvoiceCreateService {
    
    public static final String SLASH = '/';
    public static final String EMPTY = '';
    public static final String INVOICEID_NOT_PROVIDED_MESSAGE = 'Invoice ID was not provided';
    public static final String INVOICE_NOT_FOUND_MESSAGE = 'Invoice not found';
    public static final String WRAPPER_MAPPING_ERROR_MESSAGE = 'Error mapping JSON to InvoiceCreateWrapper';

   

    /**
     * @description Retrieves an `MPInvoice__c` record based on the invoice number.
     * @param invoiceNumber The invoice number.
     * @return The corresponding `MPInvoice__c` record. No se utiliza de momento
     **/
    /*
    public static MPInvoice__c getInvoiceByNumber(String invoiceNumber) {
                System.debug('invoiceNumber '+invoiceNumber);
        List<MPInvoice__c> invoicesList = [
            SELECT Id, CurrencyIsoCode
            FROM   MPInvoice__c
            WHERE  MPInvoiceNumber__c =: invoiceNumber
        ];
                System.debug('invoicesList '+invoicesList);

        if (invoicesList.isEmpty()) {
            throw new IntegrationExceptions.BusinessException(INVOICE_NOT_FOUND_MESSAGE);
        }
        return invoicesList[NumbersEnum.CERO.ordinal()];
    }*/

    /**
     * @description Validates and adjusts the wrapper based on specific business rules.
     * @param wrapper The received `InvoiceWrapper` instance.
     * @return The validated and adjusted wrapper.
     **/
    public static InvoiceWrapper validateAndFilterWrapper(InvoiceWrapper wrapper) {
        wrapper.grossAmount = getAdjustedGrossAmount(wrapper.grossAmount, wrapper.currencyIsoCode);
        return wrapper;
    }

    /**
     * @description Adjusts the gross amount based on the currency.
     * @param grossAmount The initial gross amount.
     * @param currencyIsoCode The currency ISO code.
     * @return The adjusted amount.
     **/
    private static Decimal getAdjustedGrossAmount(Decimal grossAmount, String currencyIsoCode) {
        // Adjustment logic based on the currency code (you can add specific conditions here)
        return grossAmount;  // In this example, the value is returned unchanged
    }

    /**
     * @description Creates the `Invoice__c` record and related documents.
     * @param wrapper The processed `InvoiceWrapper`.
     * @return The ID of the created invoice record.
     **/    
    public static String createInvoiceRecords(InvoiceWrapper wrapper) {
        System.debug('wrapper '+wrapper);
        Order ord = [SELECT Id, Contract.MPExternalCode__c, MP_Local__r.MPSociety__r.MPExternalCode__c
                     FROM   Order 
                     Where Contract.MPExternalCode__c =: wrapper.contractId 
                     AND  RecordType.Name = 'Término'
                     AND MPStage__c != 'Cerrado Ganado' AND MPStage__c !='Cerrado Perdido'
                     LIMIT 1]; 
        MPInvoice__c invoice = new MPInvoice__c();
        invoice.MPInvoiceNumber__c    = wrapper.invoiceNumber;
        invoice.MPCreatedAt__c        = wrapper.createdAt;
        invoice.MPGrossAmount__c      = wrapper.grossAmount;
        invoice.CurrencyIsoCode  = wrapper.currencyIsoCode;
        invoice.Orden__c = ord.Id;
        if(wrapper.relatedDocs != null){
            invoice.MPDocumentId__c = wrapper.relatedDocs[0].docId;
            invoice.MPDocumentType__c = wrapper.relatedDocs[0].docType;
            invoice.MPDescription__c = wrapper.relatedDocs[0].description;
        }
        insert invoice; 
        return invoice.Id;
    }
}