force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMaximumRetries__c.field-meta.xml
<CustomField>
    <fullName>MPMaximumRetries__c</fullName>
    <description>Numero máximo de re-intentos permitidos.</description>
    <inlineHelpText>Numero máximo de re-intentos permitidos.</inlineHelpText>
    <label>Número máximo de reintentos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPSecondsBetweenRetries__c.field-meta.xml
<CustomField>
    <fullName>MPSecondsBetweenRetries__c</fullName>
    <label>Segundos entre reintentos</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractCreationAPIUtils.cls
/**
 * @description Clase utils para crear metodos emergentes de la integracion 4.0 Creacion de contratos
 * @group Proyecto MP
 * @author Miller Mora
 * @since 20-08-2024 - Creación
 */
public with sharing class ContractCreationAPIUtils {

    //Variables para manejo de reintentos
    private static final String EMPTY = '';
    private static final String SCRIPT = '-';
    private static final String QUESTION_MARK = ' ? ';
    private static final String SPACE = ' ';
    /** Número máximo de reintentos a la API */
    private static final Integer MAX_RETRIES = (Integer) MPIntegrationSetting__mdt.getInstance('MPContractCreation').MPMaximumRetries__c;
    /** Nombre de la integración */
    private static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPContractCreation').DeveloperName;
    /** Segundos entre cada intento */
    private static final Integer SECONDS_BETWEEN_RETRIES = (Integer) MPIntegrationSetting__mdt.getInstance('MPContractCreation').MPSecondsBetweenRetries__c;


    /**
    * @description Prepara el mapa que relaciona los IDs de contratos con sus requests.
    * @param lstContract Lista de IDs de contratos.
    * @param contractWrapperSAP Wrapper que contiene la lista de requests.
    * @return Mapa que relaciona IDs de contratos con sus requests.
    */
    public static Map<Id, ContractWrapperSAP.Request> prepareContractRequestMap(List<Id> lstContract, ContractWrapperSAP contractWrapperSAP) {
        // Obtener datos necesarios para hacer la petición 
        contractWrapperSAP.lstRequest = BusinessRuleDataFactory.getContractDetails(lstContract);

        Map<Id, ContractWrapperSAP.Request> contractRequestMap = new Map<Id, ContractWrapperSAP.Request>();
        for (Integer i = 0; i < lstContract.size(); i++) {
            contractRequestMap.put(lstContract[i], contractWrapperSAP.lstRequest[i]);
        }
        return contractRequestMap;
    }

    /**
    * @description Crea un mapa que relaciona el número de contrato con su ID.
    * @param contractIds Lista de IDs de contratos.
    * @return Mapa que relaciona el número de contrato con su ID.
    */
    public static Map<String, Id> createContractNumberToIdMap(List<Id> contractIds) {
        Map<String, Id> contractNumberToIdMap = new Map<String, Id>();

        // Obtener los contratos y mapear ContractNumber a Id
        List<Contract> contracts = [SELECT Id, ContractNumber, MPExternalCode__c FROM Contract WHERE Id IN :contractIds];
        for (Contract contract : contracts) {
            contractNumberToIdMap.put(contract.ContractNumber, contract.Id);
        }
        return contractNumberToIdMap;
    }

    /**
    * @description Actualiza los IDs externos de los contratos basándose en la respuesta de la API.
    * @param contractNumberToIdMap Mapa que relaciona el número de contrato con su ID.
    * @param responses Lista de respuestas de la API.
    */
    public static void updateContractExternalIds(Map<String, Id> contractNumberToIdMap, List<ContractWrapperSAP.Response> responses) {
        List<Contract> contractsToUpdate = new List<Contract>();

        for (ContractWrapperSAP.Response response : responses) {
            if (contractNumberToIdMap.containsKey(response.offerId)) {
                Contract contractToUpdate = new Contract();
                contractToUpdate.Id = contractNumberToIdMap.get(response.offerId);
                contractToUpdate.MPExternalCode__c = response.contractId;
                contractsToUpdate.add(contractToUpdate);
            }
        }

        if (!contractsToUpdate.isEmpty()) {
            update contractsToUpdate;
        }
    }

    /**
    * @description Actualiza los registros de integración con la respuesta de la API.
    * @param integrationLogs Los registros de integración que se actualizarán.
    * @param status El estado de la integración (Exito/Error).
    * @param responseBody El cuerpo de la respuesta de la API.
    * @param errorMessage Mensaje de error en caso de que exista.
    */
    public static void updateIntegrationLogs(Id integrationStatusId, String status, String responseBody, String errorMessage,Map<Id, ContractWrapperSAP.Request> contractRequestMap, Decimal httpCode) {

        MPIntegrationStatus__c integrationLog = [SELECT Id, MPParentId__c FROM MPIntegrationStatus__c WHERE Id = :integrationStatusId LIMIT 1];
            integrationLog.MPStatus__c = status;
            integrationLog.MPResponse__c = responseBody;
            integrationLog.MPResponseDateTime__c = System.now();
            integrationLog.MPSalesforceException__c = errorMessage;
            String individualRequestPayload = JSON.serialize(contractRequestMap.get(integrationLog.MPParentId__c));
            integrationLog.MPRequest__c = individualRequestPayload;
            integrationLog.MPRequestDateTime__c = System.now();
            integrationLog.MPHttpCode__c = httpCode;

            System.debug('integrationLog > ' + integrationLog); 


        update integrationLog;
    }

}