force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/MPInvoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FCT-{00000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPInvoice__c/fields/MPDocumentId__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentId__c</fullName>
    <label>ID de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPDocumentType__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentType__c</fullName>
    <label>Tipo de Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>MPInvoiceNumber__c</fullName>
    <label>Número de Factura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>MPPaymentDate__c</fullName>
    <label>Fecha de Pago</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPPercentagePayment__c.field-meta.xml
<CustomField>
    <fullName>MPPercentagePayment__c</fullName>
    <label>Porcentaje de Pago</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/MPValidFrom__c.field-meta.xml
<CustomField>
    <fullName>MPValidFrom__c</fullName>
    <label>Válido Desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MPTermination</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Order/fields/MPStage__c.field-meta.xml
<CustomField>
    <fullName>MPStage__c</fullName>
    <label>Etapa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activación de Término</fullName>
            </value>
            <value>
                <fullName>Negociación</fullName>
            </value>
            <value>
                <fullName>Condición de Pago</fullName>
            </value>
            <value>
                <fullName>Deshabilitación</fullName>
            </value>
            <value>
                <fullName>Proceso Judicial</fullName>
            </value>
            <value>
                <fullName>Cerrado Ganado</fullName>
            </value>
            <value>
                <fullName>Cerrado Perdido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/MPTermination.recordType-meta.xml
<RecordType>
    <fullName>MPTermination</fullName>
    <active>true</active>
    <label>Término</label>
</RecordType>

force-app/main/default/classes/InvoicePaidService.cls
/**
 * @description Service class containing logic required for the InvoicePaidAPI class
 * @group MP Project
 * @author Juan Felipe Muriel
 * @since 10-31-2024 - Creation
 * @TestClass InvoicePaidAPITest
 */
public with sharing class InvoicePaidService {

    /** Error message when the request body is not as expected */
    public static final string WRAPPER_MAPPING_ERROR_MESSAGE = Label.MPMappingError;
    /** Error message when the contractId is not provided */
    public static final string CONTRACTID_NOT_PROVIDED_MESSAGE = Label.MPContractIdNotProvidedMsg;
    /** Error message when the invoice number is not provided */
    public static final string INVOICE_NUMBER_NOT_PROVIDED_MESSAGE = Label.MPInvoiceNumberNotProvidedMsg;
    /** Error message when the invoice is not found */
    public static final string INVOICE_NOT_FOUND_MESSAGE = Label.MPInvoiceNotFound;
    /** Error message when the invoice is not found */
    public static final String INVOICE_ERROR_UPDATE_MESSAGE = Label.MPInvoiceErrorUpdateMsg;
    public static final String CLOSED_WON_ORDER_STATUS = Label.MPOrderClosedWonStatus;
    public static final String CLOSED_LOST_ORDER_STATUS = Label.MPOrderClosedLostStatus;
    public static final Id TERMINATION_ORDER_RT_ID = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('MPTermination').getRecordTypeId();
    
    /**
     * @description This class extends the InvoiceWrapper class which contains the main attributes of the 
     * invoice in SAP. Additional fields used in the 24.2 integration are added. 
     */
    public class InvoicePaidWrapper extends InvoiceWrapper{
        public InvoicePaidWrapper() {
            super();
        }
        /** Additional request atributes for 24.2 SAP integration */
        public String validFrom { get; set; } 
        public String paymentDate { get; set; } 
        public String percentagePayment { get; set; }
    }

    /**
    * @description Takes the information received in the request body and transforms it into a data 
    * structure corresponding to InvoicePaidWrapper class, that contains the expected attributes.
    * @author Juan Felipe Muriel | 10-31-2024
    * @param requestJson request body
    * @return Request body in ContractTermWrapper format.
    */
    public static InvoicePaidWrapper getWrapper(String requestJson){
        InvoicePaidWrapper invoiceWrapper = new InvoicePaidWrapper();
        try {
            invoiceWrapper = (InvoicePaidWrapper) JSON.deserialize(requestJson, InvoicePaidWrapper.class);
        } catch (Exception e) { 
            throw new IntegrationExceptions.BusinessException(WRAPPER_MAPPING_ERROR_MESSAGE + ' ' + Utilities_cls.getSalesforceStackTrace(e));
        }
        return invoiceWrapper;
    }

    /** 
    * @description Run data validations
    * @author Juan Felipe Muriel | 10-31-2024
    * @param requestJson request body
    */
    public static void validateWrapper(InvoicePaidService.InvoicePaidWrapper invoiceWrapper){
        if(String.isBlank(invoiceWrapper.contractId)){
            throw new IntegrationExceptions.BusinessException(CONTRACTID_NOT_PROVIDED_MESSAGE);
        }
        if(String.isBlank(invoiceWrapper.invoiceNumber)){
            throw new IntegrationExceptions.BusinessException(INVOICE_NUMBER_NOT_PROVIDED_MESSAGE);
        }
    }

    /**
    * @description Gets the invoice record that matches the external contract id and other order conditions
    * @author Juan Felipe Muriel | 10-31-2024 
    * @param invoiceWrapper Invoice data in wrapper format
    * @return Invoice record.
    */
    public static MPInvoice__c getInvoice(InvoicePaidService.InvoicePaidWrapper invoiceWrapper){
        List<MPInvoice__c> invoiceList = new List<MPInvoice__c>();
        invoiceList = [
            SELECT   Id
            FROM     MPInvoice__c 
            WHERE    MPInvoiceNumber__c =:  invoiceWrapper.invoiceNumber
            AND      Orden__r.RecordType.Id =: TERMINATION_ORDER_RT_ID
            AND      Orden__r.Contract.MPExternalCode__c =: invoiceWrapper.contractId
            AND      (Orden__r.MPStage__c !=: CLOSED_WON_ORDER_STATUS OR Orden__r.MPStage__c !=: CLOSED_LOST_ORDER_STATUS)
            ORDER BY CreatedDate DESC
        ];

        if(invoiceList.isEmpty()){
            throw new IntegrationExceptions.BusinessException(INVOICE_NOT_FOUND_MESSAGE);
        }
        return invoiceList[NumbersEnum.CERO.ordinal()];
    }

    /**
    * @description Add new invoice data with the incoming information from the integration.
    * @author Juan Felipe Muriel | 10-31-2024
    * @param invoiceWrapper Invoice data in wrapper format
    * @param invoiceRecord Invoice record to update
    * @return invoice to update
    */
    public static MPInvoice__c addInvoiceData(InvoicePaidService.InvoicePaidWrapper invoiceWrapper, MPInvoice__c invoiceRecord){
        
        invoiceRecord.MPInvoiceNumber__c = String.isNotBlank(invoiceWrapper.invoiceNumber) ? invoiceWrapper.invoiceNumber : null;
        invoiceRecord.MPValidFrom__c = String.isNotBlank(invoiceWrapper.validFrom) ? Date.valueOf(invoiceWrapper.validFrom) : null;
        invoiceRecord.MPPaymentDate__c = String.isNotBlank(invoiceWrapper.paymentDate) ? Date.valueOf(invoiceWrapper.paymentDate) : null;
        String percentagePaymentSt = String.isNotBlank(invoiceWrapper.percentagePayment) ? invoiceWrapper.percentagePayment : null;
        if(String.isNotBlank(percentagePaymentSt)){
            invoiceRecord.MPPercentagePayment__c = Decimal.valueOf(percentagePaymentSt);
        }
        if(!invoiceWrapper.relatedDocs.isEmpty()){
            InvoiceWrapper.RelatedDoc relDoc =invoiceWrapper.relatedDocs[NumbersEnum.CERO.ordinal()];
            invoiceRecord.MPDocumentId__c = String.isNotBlank(relDoc.docId) ? relDoc.docId : null;
            invoiceRecord.MPDocumentType__c = String.isNotBlank(relDoc.docType) ? relDoc.docType : null;
            invoiceRecord.MPDescription__c = String.isNotBlank(relDoc.description) ? relDoc.description : null;
        }
        return invoiceRecord;
    }

    /**
    * @description Updates the invoice in the database with the incoming information from the integration
    * @author Juan Felipe Muriel | 10-31-2024
    * @param invoiceRecord Invoice record to update
    */
    public static void updateInvoice(MPInvoice__c invoiceRecord){
        try {
            update invoiceRecord;
        } catch (Exception e) {
            throw new IntegrationExceptions.BusinessException(INVOICE_ERROR_UPDATE_MESSAGE + ' ' + Utilities_cls.getSalesforceStackTrace(e));
        }
    }
}