force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParams__c.field-meta.xml
<CustomField>
    <fullName>MPParams__c</fullName>
    <description>Parametros agregados al cuerpo de la solicitud</description>
    <label>Parámetros</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <inlineHelpText>La fecha de fin del contrato se calcula según el tipo de registro de la oportunidad:
Nuevo Ingreso: Se calcula sumando el plazo al inicio del contrato en meses o años, según el tipo de plazo.
Modificación/Renovación: La fecha se obtiene directamente de la integración &quot;Obtener Contrato 4.1&quot; al momento de crear la oportunidad.</inlineHelpText>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPContractPeriodYears__c.field-meta.xml
<CustomField>
    <fullName>MPContractPeriodYears__c</fullName>
    <label>Plazo de contrato</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPTermType__c.field-meta.xml
<CustomField>
    <fullName>MPTermType__c</fullName>
    <label>Tipo de Plazo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meses</fullName>
            </value>
            <value>
                <fullName>Años</fullName>
                <default>true</default>
                <label>Años</label>
            </value>
            <value>
                <fullName>Días</fullName>
                <isActive>false</isActive>
                <label>Días</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPUpdateByGetContractIntegration__c.field-meta.xml
<CustomField>
    <fullName>MPUpdateByGetContractIntegration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Actualizada por Get Contract 4.1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPContractAM__c.field-meta.xml
<CustomField>
    <fullName>MPContractAM__c</fullName>
    <label>Valor AM Contrato SAP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPContractEndDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractEndDate__c</fullName>
    <label>Fecha final del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPLastInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>MPLastInvoiceDate__c</fullName>
    <label>Fecha ultima de facturación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/GetContractAPIUtils.cls
/**
 * @description
 * @group Proyecto MP
 * @author Miller
 * @since 28-08-2024 - Creación
 */
public with sharing class GetContractAPIUtils {

    /** Nombre de la integración */
    public static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPGETContract').DeveloperName;
    public static final String AM15_STRING = 'AM15';
    public static final String AM90_STRING = 'AM90';

    /**
    * @description Método el cual modifica los valores del log de integracion antes de hacer UPDATE
    * @author Miller Mora | 20-08-2024 
    * @param callManager Instancia del callManager
    * @return updatedIntStat Registro de log de la transacción actualizado
    **/
    public static MPIntegrationStatus__c modifyIntegrationLog(GetContractAPICallManager callManager){
        MPIntegrationStatus__c updatedIntStat  = callManager.getIntegrationStatus();
        updatedIntStat.MPIntegrationName__c    = INTEGRATION_NAME;
        updatedIntStat.MPParentId__c           = callManager.getParentId();
        updatedIntStat.MPStatus__c             = callManager.getContractAPIWrapper().status;
        updatedIntStat.MPRequest__c            = JSON.serialize(callManager.getContractAPIWrapper().request);
        updatedIntStat.MPRequestDateTime__c    = callManager.getContractAPIWrapper().requestDateTime;
        updatedIntStat.MPResponse__c           = callManager.getContractAPIWrapper().response.message;
        updatedIntStat.MPResponseDateTime__c   = callManager.getContractAPIWrapper().requestDateTime;
        updatedIntStat.MPParams__c             = JSON.serialize(callManager.getContractAPIWrapper().params);
        updatedIntStat.MPSalesforceException__c= callManager.getContractAPIWrapper().salesforceErrorMessage;
        updatedIntStat.MPHttpCode__c           = callManager.getContractAPIWrapper().httpCode;
        System.debug('updatedIntStat' + updatedIntStat);
        return updatedIntStat;
    }

    public static void updateOpportunityWithEndDate(Opportunity opp, String jsonResponse) {
        System.debug('JSON Response: ' + jsonResponse);
        Map<String, Object> jsonMap = (Map<String, Object>) JSON.deserializeUntyped(jsonResponse);
        String endDateStr = (String)jsonMap.get('endDate');
        
        if (endDateStr != null) {           
            Date endDate = Date.valueOf(endDateStr.split('T')[0]);
            System.debug('Parsed endDate: ' + endDate);

            Date startDate = Date.today();
            System.debug('Start Date (Fecha de Creación de la Oportunidad): ' + startDate);
            
            // Calcular diferencia en meses entre la fecha de inicio y la fecha de fin
            Integer monthsDifference = calculateMonthsDifference(startDate, endDate);
            System.debug('Months Difference: ' + monthsDifference);
            
            // Actualizar el campo MPContractPeriodYears__c con la diferencia de meses
            opp.MPContractPeriodYears__c = monthsDifference;
            
            // Asignar el valor del campo 'MPUpdateByGetContractIntegration__c' a true
            opp.MPUpdateByGetContractIntegration__c = TRUE;

            opp.MPContractEndDate__c = endDate;
            update opp;
            System.debug('Opportunity updated with MPContractEndDate__c, MPContractPeriodYears__c, and MPTermType__c.' + monthsDifference);

        }else {
            System.debug('No endDate found in JSON response.');
        }
    }

    // Método auxiliar para calcular la diferencia en meses entre dos fechas
    public static Integer calculateMonthsDifference(Date startDate, Date endDate) {
      
        System.debug('Start Date (Fecha de inicio): ' + startDate);
        System.debug('End Date (Fecha de fin): ' + endDate);
        
        Integer monthsDifference = startDate.monthsBetween(endDate);
        
        System.debug('Months Difference (Diferencia en meses): ' + monthsDifference);
        return monthsDifference;
    }

    /**
    * @description Modify Order details after every Get Contract CallOut
    * @author Juan Felipe | 10-21-2024 
    * @param parentId Order Id
    * @param getContractAPIWrapper Get Contract API Response
    **/
    public static void updateOrder(Id parentId, String responseJson) {

        TerminationOrderWrapper terminationOrderWrapper = (TerminationOrderWrapper) JSON.deserialize(responseJson, TerminationOrderWrapper.class);
        Order orderTemp = new Order();
        orderTemp.Id = parentId;
        orderTemp.MPContractEndDate__c = String.isNotBlank(terminationOrderWrapper.endDate) ? Date.valueOf(terminationOrderWrapper.endDate) : null;
        orderTemp.MPLastInvoiceDate__c = String.isNotBlank(terminationOrderWrapper.lastInvoiceDate) ? Date.valueOf(terminationOrderWrapper.lastInvoiceDate) : null;
        
        if(terminationOrderWrapper.condition != null) {
            for(ContractWrapper.Condition condition : terminationOrderWrapper.condition){
                if(condition.type == AM15_STRING || condition.type == AM90_STRING) {
                    orderTemp.MPContractAM__c = condition.unitPrice;
                    continue;
                }
            }
        }

        update orderTemp;
    }

    public class TerminationOrderWrapper {
        String endDate;
        List<ContractWrapper.Condition> condition;
        String lastInvoiceDate;
    }
}