force-app/main/default/objects/Account/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>External Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MPIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>MPIdentificationNumber__c</fullName>
    <label>Número de Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MPIdentificationType__c.field-meta.xml
<CustomField>
    <fullName>MPIdentificationType__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIdentificationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MPContactRole__c.field-meta.xml
<CustomField>
    <fullName>MPContactRole__c</fullName>
    <label>Función de Contacto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Codeudor</fullName>
            </value>
            <value>
                <fullName>Contacto cobranza</fullName>
            </value>
            <value>
                <fullName>Contacto principal</fullName>
            </value>
            <value>
                <fullName>Encargado inmobiliario</fullName>
            </value>
            <value>
                <fullName>Representante legal 1</fullName>
            </value>
            <value>
                <fullName>Representante legal 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MPIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>MPIdentificationNumber__c</fullName>
    <label>Número de Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MPIdentificationType__c.field-meta.xml
<CustomField>
    <fullName>MPIdentificationType__c</fullName>
    <label>Tipo de Identificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIdentificationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/MPBrand__c.field-meta.xml
<CustomField>
    <fullName>MPBrand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marca</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Brand)</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPMall__c.field-meta.xml
<CustomField>
    <fullName>MPMall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mall</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Mall</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Mall)</relationshipLabel>
    <relationshipName>MPMallContracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPContractTerminationRecords__c/MPContractTerminationRecords__c.object-meta.xml
<CustomObject>
    <label>FTC</label>
    <nameField>
        <displayFormat>FTC-{0000}</displayFormat>
        <label>FTC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractTerminationRecords__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <label>Solicitada</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>Recibida</label>
            </value>
            <value>
                <fullName>Socialized</fullName>
                <label>Socializada</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <label>Aceptada</label>
            </value>
            <value>
                <fullName>RejectedByItems</fullName>
                <label>Rechazada por Items</label>
            </value>
            <value>
                <fullName>RejectedByExceptionAndOrSpecialConditionToApply</fullName>
                <label>Rechazada por Excepción y/o Condición Especial por Aplicar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPMall__c.field-meta.xml
<CustomField>
    <fullName>MPMall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mall</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Mall</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Locales (Mall)</relationshipLabel>
    <relationshipName>MPMallStores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/MPTerminationRecord__c.object-meta.xml
<CustomObject>
    <label>Elemento de Ficha de Término</label>
    <nameField>
        <displayFormat>EFT-{0000}</displayFormat>
        <label>Elemento de Ficha de Término</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elementos de Ficha de Término</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPCategory__c.field-meta.xml
<CustomField>
    <fullName>MPCategory__c</fullName>
    <label>Categoría</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPDescription__c.field-meta.xml
<CustomField>
    <fullName>MPDescription__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPDocumentDueDate__c.field-meta.xml
<CustomField>
    <fullName>MPDocumentDueDate__c</fullName>
    <label>Fecha de vencimiento del documento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPItemCode__c.field-meta.xml
<CustomField>
    <fullName>MPItemCode__c</fullName>
    <label>Código de artículo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPReferenceDocument__c.field-meta.xml
<CustomField>
    <fullName>MPReferenceDocument__c</fullName>
    <label>Documento de referencia</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPTerminationRecord__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Aprobado</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>Rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MP_Local__c.field-meta.xml
<CustomField>
    <fullName>MP_Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPContractStartDate__c.field-meta.xml
<CustomField>
    <fullName>MPContractStartDate__c</fullName>
    <label>Fecha de inicio del contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPExceptionApproval__c.field-meta.xml
<CustomField>
    <fullName>MPExceptionApproval__c</fullName>
    <label>Aprobación de Excepción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPApprovalField</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MPExitDate__c.field-meta.xml
<CustomField>
    <fullName>MPExitDate__c</fullName>
    <description>Campo creado para tener la información de la fecha de entrega del local cuando hay una terminación de contrato</description>
    <label>Fecha de Salida</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPFTCPrincipal__c.field-meta.xml
<CustomField>
    <fullName>MPFTCPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FTC Principal</label>
    <referenceTo>MPContractTerminationRecords__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPLastInvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>MPLastInvoiceDate__c</fullName>
    <label>Fecha ultima de facturación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPNumberOfInstalments__c.field-meta.xml
<CustomField>
    <fullName>MPNumberOfInstalments__c</fullName>
    <inlineHelpText>Se ingresa un valor sugerido el cual será aprobado por riesgos</inlineHelpText>
    <label>Numero de pagarés</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPPaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>MPPaymentMethod__c</fullName>
    <label>Forma de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documentada</fullName>
            </value>
            <value>
                <fullName>Transferencia_con_garantías</fullName>
                <label>Transferencia con garantías</label>
            </value>
            <value>
                <fullName>Transferencia_sin_garantías</fullName>
                <label>Transferencia sin garantías</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MPSpecialConditionAmount__c.field-meta.xml
<CustomField>
    <fullName>MPSpecialConditionAmount__c</fullName>
    <label>Monto condición especial por aplicar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPSpecialConditionInFavorOf__c.field-meta.xml
<CustomField>
    <fullName>MPSpecialConditionInFavorOf__c</fullName>
    <label>A favor de</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mallplaza</fullName>
            </value>
            <value>
                <fullName>Socio comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/MPSpecialConditionToApply__c.field-meta.xml
<CustomField>
    <fullName>MPSpecialConditionToApply__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condición Especial por Aplicar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPWarrantyUse__c.field-meta.xml
<CustomField>
    <fullName>MPWarrantyUse__c</fullName>
    <label>Uso de garantía</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aplicar Garantías</fullName>
            </value>
            <value>
                <fullName>Devolución de Garantías</fullName>
                <default>true</default>
                <label>Devolución de Garantías</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TermsPDF_Ctrl.cls
/**
 * @description Controller of TermsPDF.vfp
 * @group Proyecto MP
 * @author Marco Guevara (MG)
 * @since 29-10-2024 - Creación
 */
public class TermsPDF_Ctrl {
    public List<User> lstOwner { get; set; }
    public List<Order> lstOrder { get; set; }

    public List<Contact> lstContact { get; set; }

    public List<MPTerminationRecord__c> lstTerminationRecord { get; set; }
    public List<MPTerminationRecord__c> lstTerminationRecordIssued { get; set; }
    public List<MPTerminationRecord__c> lstTerminationRecordOperationalDebt { get; set; }
    public List<MPTerminationRecord__c> lstTerminationRecordComercialDebt { get; set; }
    public List<MPTerminationRecord__c> lstTerminationRecordAnticipatedConceptsAdjustment { get; set; }
    public List<MPTerminationRecord__c> lstTerminationRecordWarranty { get; set; }

    public String strLocalCode { get; set; }
    public String strRecordId { get; set; }
    public Double dblTotalDebt { get; set; }
    public Double dblSubTotalOperationalDebt { get; set; }
    public Double dblSubTotalComercialDebt { get; set; }
    public Double dblSubTotalAnticipatedConceptsAdjustment { get; set; }
    public Double dblSubTotalIssuedDebt { get; set; }

    public Boolean blnIsDraft { get; set; }

    public TermsPDF_Ctrl(){
        this.blnIsDraft = true;
        this.lstOwner = new List<User>();
        this.lstContact = new List<Contact>();
        this.lstOrder = new List<Order>();

        this.lstTerminationRecord = new List<MPTerminationRecord__c>();
        this.lstTerminationRecordIssued = new List<MPTerminationRecord__c>();
        this.lstTerminationRecordOperationalDebt = new List<MPTerminationRecord__c>();
        this.lstTerminationRecordComercialDebt = new List<MPTerminationRecord__c>();
        this.lstTerminationRecordAnticipatedConceptsAdjustment = new List<MPTerminationRecord__c>();
        this.lstTerminationRecordWarranty = new List<MPTerminationRecord__c>();

        this.dblSubTotalOperationalDebt = this.dblSubTotalComercialDebt = this.dblSubTotalAnticipatedConceptsAdjustment = this.dblSubTotalIssuedDebt = this.dblTotalDebt = 0;
        this.strLocalCode = '';        

        // get order id from the parammeter
        this.strRecordId=ApexPages.currentPage().getParameters().get('id');

		this.lstOrder = [select id,MPExitDate__c,ownerid,toLabel(MPPaymentMethod__c),MPContractStartDate__c,Contract.MPMall__r.name,Contract.MPMall__r.MPExternalCode__c,Contract.MPBrand__r.name,
                         Contract.accountid,Contract.account.name,Contract.account.MPIdentificationNumber__c,Contract.account.MPIdentificationType__c,Contract.account.billingStreet,
                         Contract.account.billingCity,Contract.account.billingCountry,Contract.account.billingState,contract.MPExternalCode__c,MPSpecialConditionToApply__c,MPExceptionApproval__c,
                         Contract.CurrencyIsoCode,toLabel(MPSpecialConditionInFavorOf__c),MPSpecialConditionAmount__c,MPWarrantyUse__c,MPNumberOfInstalments__c,MP_Local__c,MPFTCPrincipal__r.MPStatus__c,
                         MPLastInvoiceDate__c
                         from Order where id =: strRecordId];
        if(this.lstOrder.size()>0){
            if(this.lstOrder[0].MPFTCPrincipal__r.MPStatus__c != 'Socialized'){
                this.blnIsDraft = false;
            }
            
            this.lstContact = [select id,name,MPIdentificationType__c,MPIdentificationNumber__c from contact where accountid =:this.lstOrder[0].Contract.accountid and MPContactRole__c includes ('Representante legal 1','Representante legal 2')];
            
            this.lstOwner = [select id,name,manager.name,manager.manager.name from user where id =:this.lstOrder[0].ownerid];
            
            this.lstTerminationRecord = [select id,MPCategory__c,MPItemCode__c,MPDescription__c,MPReferenceDocument__c,MPStatus__c,MPDocumentDueDate__c,MPDocumentDate__c,FTC__c,
                                         MPDocumentNumber__c,MPSubcategory__c,MPDocumentType__c,MPOperationType__c,MPItemValue__c
                                         from MPTerminationRecord__c where FTC__r.MPOrder__c =: this.strRecordId];
            
            List<MPRentalObjectByStore__c> lstRentalObjectByStore = [select id,MPRentalObject__r.MPExternalCode__c from MPRentalObjectByStore__c where MPStore__c =: this.lstOrder[0].MP_Local__c];
            
            for(MPRentalObjectByStore__c iRentalObjectByStore:lstRentalObjectByStore){
                strLocalCode += (','+iRentalObjectByStore.MPRentalObject__r.MPExternalCode__c);
            }
            strLocalCode = strLocalCode.right(strLocalCode.length()-1);
            
            if(lstOrder[0].MPSpecialConditionAmount__c != null){
                this.dblTotalDebt = ((lstOrder[0].MPSpecialConditionInFavorOf__c=='Mallplaza'?1:-1)*lstOrder[0].MPSpecialConditionAmount__c);   
            }            	
            
            for(MPTerminationRecord__c i : this.lstTerminationRecord){
                if(i.MPCategory__c =='Emitida'){
                    this.lstTerminationRecordIssued.add(i);
                    this.dblSubTotalIssuedDebt += i.MPItemValue__c;
                    if(lstOrder[0].MPExceptionApproval__c != 'Aprobado'){
                        this.dblTotalDebt += i.MPItemValue__c;
                    }
                }else if(i.MPCategory__c =='Garantia'){
                    this.lstTerminationRecordWarranty.add(i);
                }else if(i.MPCategory__c =='PorEmitir' && i.MPSubcategory__c=='DEUDAOPE'){
                    this.dblSubTotalOperationalDebt += i.MPItemValue__c;
                    this.lstTerminationRecordOperationalDebt.add(i);
                    this.dblTotalDebt += i.MPItemValue__c;
                }else if(i.MPCategory__c =='PorEmitir' && i.MPSubcategory__c=='DEUDACOM'){
                    this.dblSubTotalComercialDebt += i.MPItemValue__c;
                    this.lstTerminationRecordComercialDebt.add(i);
                    this.dblTotalDebt += i.MPItemValue__c;
                }else if(i.MPCategory__c =='PorEmitir' && i.MPSubcategory__c=='AJUSCANT'){
                    this.dblSubTotalAnticipatedConceptsAdjustment += i.MPItemValue__c;
                    this.lstTerminationRecordAnticipatedConceptsAdjustment.add(i);
                    this.dblTotalDebt += i.MPItemValue__c;
                }
            }
        }
    }
}