force-app/main/default/objects/Account/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>External Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/MPAdjustment__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado que permite generar ajustes en las clases de condición reajustables de acuerdo al tipo de contrato al que pertenecen.</description>
    <label>Ajuste</label>
    <nameField>
        <label>Nombre Ajuste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ajustes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPAdjustment__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPBusinessType__c/MPBusinessType__c.object-meta.xml
<CustomObject>
    <label>Tipo de Negocio</label>
    <nameField>
        <label>Business Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Negocio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPCalculationRule__c/MPCalculationRule__c.object-meta.xml
<CustomObject>
    <label>Norma de Cálculo</label>
    <nameField>
        <label>Norma de Cálculo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Normas de Cálculo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractTerminationRecords__c/MPContractTerminationRecords__c.object-meta.xml
<CustomObject>
    <label>FTC</label>
    <nameField>
        <displayFormat>FTC-{0000}</displayFormat>
        <label>FTC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FTC</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPContractTerminationRecords__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <label>Solicitada</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <label>Recibida</label>
            </value>
            <value>
                <fullName>Socialized</fullName>
                <label>Socializada</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <label>Aceptada</label>
            </value>
            <value>
                <fullName>RejectedByItems</fullName>
                <label>Rechazada por Items</label>
            </value>
            <value>
                <fullName>RejectedByExceptionAndOrSpecialConditionToApply</fullName>
                <label>Rechazada por Excepción y/o Condición Especial por Aplicar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPInvoice__c/MPInvoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FCT-{00000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPInvoice__c/fields/MPInvoicePaidAPIStatus__c.field-meta.xml
<CustomField>
    <fullName>MPInvoicePaidAPIStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles API 24.2</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Facturas (Detalles API 24.2)</relationshipLabel>
    <relationshipName>Facturas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPInvoice__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>Orden</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>MPTermination</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/MPOrderCondition__c.object-meta.xml
<CustomObject>
    <label>Condiciones de Pedido</label>
    <nameField>
        <displayFormat>OC{00000}</displayFormat>
        <label>Order Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPOrderCondition__c/fields/MPAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de ajuste</label>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de cálculo</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo Lookup hacia el registro en el objeto MPIntegrationStatus__c el cual muestra un Log de las integraciones</description>
    <label>Detalle de la integración</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPQuoteCondition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPRentalObjectByStore__c/MPRentalObjectByStore__c.object-meta.xml
<CustomObject>
    <label>Objeto de Alquiler por Local</label>
    <nameField>
        <displayFormat>ROS-{000000}</displayFormat>
        <label>Rental Object By Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos de Alquiler por Local</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPRentalObjectByStore__c/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Objetos de Alquiler</relationshipLabel>
    <relationshipName>RentalObjectsByStore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPFTCPrincipal__c.field-meta.xml
<CustomField>
    <fullName>MPFTCPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FTC Principal</label>
    <referenceTo>MPContractTerminationRecords__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>External Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoicePaidAPITest.cls
/**
 * @description       : 
 * @author            : Juan Felipe Muriel
 * @group             : 
 * @last modified on  : 01-11-2024
 * @last modified by  : Juan Felipe Muriel
**/
@isTest
private class InvoicePaidAPITest {

    @testSetup
    static void setup(){
        /**Crear pricebook (Condicion de contrato) */
        Pricebook2 contractType = Build.anPricebook2()
        .withName('Contrato Comercial Perú')
        .withMPPaymentCondition('MP12')
        .withMPIsProRataMethod(true)
        .withMPExternalCode('P101')
        .withIsActive(true)
        .withCurrencyIsoCode('PEN')
        .build();
        insert contractType;
        /**Fin pricebook (Condicion de contrato) */

        /**Crear tipos de negocio */
        MPBusinessType__c sector = Build.anMPSector()
        .withName('Burger Food')
        .withMPExternalCode('S-000001')
        .withMPCategory('Autoplaza')
        .withCurrencyIsoCode('PEN')
        .build();
        MPBusinessType__c businessUnit = Build.anMPBusinessUnit()
        .withName('Fast Food')
        .withMPExternalCode('B-000001')
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<MPBusinessType__c>{sector,businessUnit};
        /**Fin tipos de negocio */

        /**Crear cuentas */
        Account parentAcc = Build.anMPAccount()
        .withName('Parent Account')
        .withAccountCurrency('PEN')
        .build();
        insert parentAcc;

        Account brandAccount = Build.anBrandAccount()
        .withName('Brand Account 01')
        .withAccountCurrency('PEN')
        .withParentAccount(parentAcc)
        .withMPSector(sector)
        .build();
        Account mallAccount = Build.anMallAccount()
        .withName('Mall Account 01')
        .withAccountCurrency('PEN')
        .withMPExternalCode('PNO')
        .build();
        Account societyAccount = Build.anSocietyAccount()
        .withName('Society Account 01')
        .withAccountCurrency('PEN')
        .withMPExternalCode('1200')
        .build();
        insert new List<Account>{brandAccount, mallAccount, societyAccount} ;
        /**Fin crear cuentas */

        /**Crear locales y Objetos de alquiler */
        MPStore__c store = Build.anLocal()
        .withName('Local 1001')
        .withMPMall(mallAccount)
        .withMPFootage(100)
        .withMPExternalCode('store-0001')
        .withMPCeBe('cebe-001')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        MPStore__c rentalObject1 = Build.anMPRentalObject()
        .withName('OA 1001')
        .withMPMall(mallAccount)
        .withMPFootage(30)
        .withMPExternalCode('OA1001EXID')
        .withMPCeBe('')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        MPStore__c rentalObject2 = Build.anMPRentalObject()
        .withName('OA 1002')
        .withMPMall(mallAccount)
        .withMPFootage(30)
        .withMPExternalCode('OA1002EXID')
        .withMPCeBe('')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        insert new List<MPStore__c>{store,rentalObject1,rentalObject2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Objeto de Alquiler por local */
        MPRentalObjectByStore__c rentalObjectByStore1 = Build.anMPRentalObjectByStore()
        .withMPRentalObject(rentalObject1)
        .withMPStore(store)
        .build();
        MPRentalObjectByStore__c rentalObjectByStore2 = Build.anMPRentalObjectByStore()
        .withMPRentalObject(rentalObject2)
        .withMPStore(store)
        .build();
        insert new List<MPRentalObjectByStore__c>{rentalObjectByStore1,rentalObjectByStore2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Oportunidad */
        Opportunity opportunity1 = Build.anOpportunity()
        .withName('opportunity1')
        .withStageName('Exploración')
        .withAccount(parentAcc)
        .withMPBrand(brandAccount)
        .withMPMall(mallAccount)
        .withCloseDate((System.now().date()))
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<Opportunity>{opportunity1};
        /**Fin Oportunidad */

        /**Crear Quote */
        Quote quote1 = Build.anQuote()
        .withName('quote1')
        .withOpportunity(opportunity1)
        .withMPStore(store)
        .withStatus('Draft')
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<Quote>{quote1};
        /**Fin Quote */

        /**Crear Quote Condition */
        MPQuoteCondition__c quoteCondition1 = Build.anQuoteCondition()
        .withMPQuote(quote1)
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<MPQuoteCondition__c>{quoteCondition1};
        /**Fin Quote Quote Condition */

        /**Crear orden */
        Order testOrder = Build.anOrder()
            .withAccount(parentAcc)
        // .withContract(testContract)
            .withStore(store)
            .withEffectiveDate(System.today())
            .withStatus('Draft')
            .withCurrencyIsoCode('PEN')
            .build();
        insert new List<Order>{testOrder};
        /**Fin orden */

        /** Crear Product2 */
        Product2 conditionClass = Build.anProduct2()
            .withIsActive(true)
            .withMPExternalCode('AP30')
            .withName('AP Fijo')
            .build();
        insert new List<Product2>{conditionClass};
        /** Fin Crear Product2 */

        /** Crear CalculationRule */
        MPCalculationRule__c calculationRule = Build.anCalculationRule()
            .withExternalCode('MPAD')
            .withName('MPAD')
            .build();
        insert new List<MPCalculationRule__c>{calculationRule};
        /** Fin Crear CalculationRule */

        /** Crear MPAdjustment__c */
        // MPAdjustment__c adjustmentType = Build.anStrategicAdjustment()
        //     .withPeriod('2')
        //     .withValue(10)
        //     .withExternalCode('MPAD2')
        //     .build();
        // insert new List<MPCalculationRule__c>{calculationRule};
        /** Fin Crear MPAdjustment__c */

        /** Crear MPOrderCondition__c */
        MPOrderCondition__c orderCondition = Build.anOrderCondition()
            .withOrder(testOrder)
            .withConditionClass(conditionClass)
            .withCalculationRule(calculationRule)
            // .withAdjustmentType(adjustmentType)
            .withStartDate(System.today())
            .withEndDate(System.today().addMonths(12))
            .withVolumenValue(100)
            .withValue(200)
            .withFinalVolumen(150)
            .withIntialVolumen(50)
            .build();
        insert new List<MPOrderCondition__c>{orderCondition};
        /** Fin Crear MPOrderCondition__c */

        /** Crear Contrato */
        Contract testContract = Build.aContract()
        .withName('Test Class Contract')
        .withAccount(parentAcc)
        .withMall(mallAccount)
        .withMarca(brandAccount)
        .withCurrencyIsoCode('PEN')
        .withStartDate(System.today())
        .withEndDate(12) // 12 meses de duración
        .withStatus('Draft')
        .withOpp(opportunity1)
        .withOrder(testOrder)
        .withExternalCode('35083')
        .build();
        insert testContract;
        /**FIN Crear Contrato */

        // Crear orden de terminacion y relacionarla con el contrato
        Order testOrderTermination = Build.anMPOrderTermination()
        .withAccount(parentAcc)
        .withContract(testContract)
        .withStore(store)
        .withEffectiveDate(System.today())
        .withStatus('Draft')
        .withStage('Activación de Término')
        .withCurrencyIsoCode('PEN')
        .build();
        insert testOrderTermination;

        /** Crear FTC */
        MPContractTerminationRecords__c testFTC = Build.anMPContractTerminationRecords()
        .withOrder(testOrderTermination)
        .withStatus('Requested')
        .build();
        insert testFTC;
        /** FIN FTC */

        // Asociar FTC principal a la orden
        testOrderTermination.MPFTCPrincipal__c = testFTC.Id;
        update testOrderTermination;

        /** Crear Factura */
        MPInvoice__c invoiceTest = Build.anMPInvoice()
        .withOrder(testOrderTermination)
        .withInvoiceNumber('invoice_001')
        .build();
        insert invoiceTest;
        /** FIN crear FTC */
    }


    @isTest
    static void testSuccess(){
        String contractId = '35083';
        String invoiceNumber = 'invoice_001';
        String companyCode = '';
        Integer httpCode = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);
        String logStatus = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        String url = '/invoices/paid';

        // Crear el objeto RestRequest para simular la solicitud entrante
        RestRequest req = new RestRequest();
        req.requestUri = url;
        req.httpMethod = 'POST';
        String requestBody = '{"invoiceNumber":"' + invoiceNumber + '","contractId":"' + contractId + '","companyCode":"","validFrom":"2024-10-30T19:40:45.947Z","paymentDate":"2024-10-30","percentagePayment":12,"relatedDocs":[{"docId":"docId_01","docType":"docType_01","description":"descripcion_test"}]}';
        req.requestBody = Blob.valueOf(requestBody);
        // Crear el objeto RestResponse para capturar la respuesta
        RestResponse res = new RestResponse();
        // Asignar el request y response simulados al contexto REST
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        // Llamar al método de la API
        InvoicePaidAPI.updateInvoice();
        Test.stopTest();

        MPInvoice__c invoice = [
            SELECT Id, MPInvoicePaidAPIStatus__r.MPStatus__c, MPInvoicePaidAPIStatus__c
            FROM   MPInvoice__c 
            WHERE  Orden__r.Contract.MPExternalCode__c =: contractId
            LIMIT  1
        ];

        // Verificar la respuesta
        Assert.isNotNull(invoice.MPInvoicePaidAPIStatus__c, 'La factura no tiene asociado ningun registro de log');
        Assert.areEqual(logStatus,invoice.MPInvoicePaidAPIStatus__r.MPStatus__c,'El log de integración debe ser exitoso');
        Assert.areEqual(httpCode, RestContext.response.statusCode, 'El código de respuesta debería ser ' + httpCode);
    }

    @isTest
    static void testContractNotFound(){
        String contractId = '111111111'; // codigo que no existe en base de datos para generar error
        String invoiceNumber = 'invoice_001';
        String companyCode = '';
        Integer httpCode = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);
        String logStatus = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        String url = '/invoices/paid';

        // Crear el objeto RestRequest para simular la solicitud entrante
        RestRequest req = new RestRequest();
        req.requestUri = url;
        req.httpMethod = 'POST';
        String requestBody = '{"invoiceNumber":"' + invoiceNumber + '","contractId":"' + contractId + '","companyCode":"","validFrom":"2024-10-30T19:40:45.947Z","paymentDate":"2024-10-30","percentagePayment":12,"relatedDocs":[{"docId":"docId_01","docType":"docType_01","description":"descripcion_test"}]}';
        req.requestBody = Blob.valueOf(requestBody);
        // Crear el objeto RestResponse para capturar la respuesta
        RestResponse res = new RestResponse();
        // Asignar el request y response simulados al contexto REST
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        // Llamar al método de la API
        InvoicePaidAPI.updateInvoice();
        Test.stopTest();

        // Verificar la respuesta
        MPIntegrationStatus__c log = [
            SELECT Id,MPStatus__c,MPResponse__c
            FROM   MPIntegrationStatus__c
            ORDER  BY CreatedDate desc
            LIMIT  1
        ];

        // Verificar la respuesta
        Assert.areEqual(logStatus,log.MPStatus__c,'El log de integración debe ser Fallido');
        Assert.areEqual(httpCode, RestContext.response.statusCode, 'El código de respuesta debería ser ' + httpCode);
    }

    @isTest
    static void testContractNotProvided(){
        String contractId = ''; // codigo que no existe en base de datos para generar error
        String invoiceNumber = 'invoice_001';
        String companyCode = '';
        Integer httpCode = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);
        String logStatus = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        String url = '/invoices/paid';

        // Crear el objeto RestRequest para simular la solicitud entrante
        RestRequest req = new RestRequest();
        req.requestUri = url;
        req.httpMethod = 'POST';
        String requestBody = '{"invoiceNumber":"' + invoiceNumber + '","contractId":"' + contractId + '","companyCode":"","validFrom":"2024-10-30T19:40:45.947Z","paymentDate":"2024-10-30","percentagePayment":12,"relatedDocs":[{"docId":"docId_01","docType":"docType_01","description":"descripcion_test"}]}';
        req.requestBody = Blob.valueOf(requestBody);
        // Crear el objeto RestResponse para capturar la respuesta
        RestResponse res = new RestResponse();
        // Asignar el request y response simulados al contexto REST
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        // Llamar al método de la API
        InvoicePaidAPI.updateInvoice();
        Test.stopTest();

        // Verificar la respuesta
        MPIntegrationStatus__c log = [
            SELECT Id,MPStatus__c,MPResponse__c
            FROM   MPIntegrationStatus__c
            ORDER  BY CreatedDate desc
            LIMIT  1
        ];

        // Verificar la respuesta
        Assert.areEqual(logStatus,log.MPStatus__c,'El log de integración debe ser Fallido');
        Assert.areEqual(httpCode, RestContext.response.statusCode, 'El código de respuesta debería ser ' + httpCode);
    }

    @isTest
    static void testInvoiceNotProvided(){
        String contractId = '35083';
        String invoiceNumber = ''; // enviando atributo vacio, para provocar error
        String companyCode = '';
        Integer httpCode = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);
        String logStatus = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        String url = '/invoices/paid';

        // Crear el objeto RestRequest para simular la solicitud entrante
        RestRequest req = new RestRequest();
        req.requestUri = url;
        req.httpMethod = 'POST';
        String requestBody = '{"invoiceNumber":"' + invoiceNumber + '","contractId":"' + contractId + '","companyCode":"","validFrom":"2024-10-30T19:40:45.947Z","paymentDate":"2024-10-30","percentagePayment":12,"relatedDocs":[{"docId":"docId_01","docType":"docType_01","description":"descripcion_test"}]}';
        req.requestBody = Blob.valueOf(requestBody);
        // Crear el objeto RestResponse para capturar la respuesta
        RestResponse res = new RestResponse();
        // Asignar el request y response simulados al contexto REST
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        // Llamar al método de la API
        InvoicePaidAPI.updateInvoice();
        Test.stopTest();

        // Verificar la respuesta
        MPIntegrationStatus__c log = [
            SELECT Id,MPStatus__c,MPResponse__c
            FROM   MPIntegrationStatus__c
            ORDER  BY CreatedDate desc
            LIMIT  1
        ];

        // Verificar la respuesta
        Assert.areEqual(logStatus,log.MPStatus__c,'El log de integración debe ser Fallido');
        Assert.areEqual(httpCode, RestContext.response.statusCode, 'El código de respuesta debería ser ' + httpCode);
    }

    @isTest
    static void testMappingError(){
        /** Vamos a pasar un 'requestBody' invalido */
        String contractId = '35083';
        String invoiceNumber = ''; // enviando atributo vacio, para provocar error
        String companyCode = '';
        Integer httpCode = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);
        String logStatus = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        String url = '/invoices/paid';

        // Crear el objeto RestRequest para simular la solicitud entrante
        RestRequest req = new RestRequest();
        req.requestUri = url;
        req.httpMethod = 'POST';
        String requestBody = '{invalid  Json}';
        req.requestBody = Blob.valueOf(requestBody);
        // Crear el objeto RestResponse para capturar la respuesta
        RestResponse res = new RestResponse();
        // Asignar el request y response simulados al contexto REST
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        // Llamar al método de la API
        InvoicePaidAPI.updateInvoice();
        Test.stopTest();

        // Verificar la respuesta
        MPIntegrationStatus__c log = [
            SELECT Id,MPStatus__c,MPResponse__c
            FROM   MPIntegrationStatus__c
            ORDER  BY CreatedDate desc
            LIMIT  1
        ];

        // Verificar la respuesta
        Assert.areEqual(logStatus,log.MPStatus__c,'El log de integración debe ser Fallido');
        Assert.areEqual(httpCode, RestContext.response.statusCode, 'El código de respuesta debería ser ' + httpCode);
    }
}