force-app/main/default/objects/Account/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>External Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/MPAdjustment__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado que permite generar ajustes en las clases de condición reajustables de acuerdo al tipo de contrato al que pertenecen.</description>
    <label>Ajuste</label>
    <nameField>
        <label>Nombre Ajuste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ajustes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPAdjustment__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/fields/MPPeriod__c.field-meta.xml
<CustomField>
    <fullName>MPPeriod__c</fullName>
    <label>Periodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/fields/MPValue__c.field-meta.xml
<CustomField>
    <fullName>MPValue__c</fullName>
    <label>Valor</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MPBusinessType__c/MPBusinessType__c.object-meta.xml
<CustomObject>
    <label>Tipo de Negocio</label>
    <nameField>
        <label>Business Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Negocio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPCalculationRule__c/MPCalculationRule__c.object-meta.xml
<CustomObject>
    <label>Norma de Cálculo</label>
    <nameField>
        <label>Norma de Cálculo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Normas de Cálculo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path__c</fullName>
    <description>Ruta de la API, despues de su raíz.</description>
    <label>Api Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMaximumRetries__c.field-meta.xml
<CustomField>
    <fullName>MPMaximumRetries__c</fullName>
    <description>Numero máximo de re-intentos permitidos.</description>
    <inlineHelpText>Numero máximo de re-intentos permitidos.</inlineHelpText>
    <label>Número máximo de reintentos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPNamedCredential__c.field-meta.xml
<CustomField>
    <fullName>MPNamedCredential__c</fullName>
    <description>Api name del Named Credential que se utiliza en la integración.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPSecondsBetweenRetries__c.field-meta.xml
<CustomField>
    <fullName>MPSecondsBetweenRetries__c</fullName>
    <label>Segundos entre reintentos</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPTimeout__c.field-meta.xml
<CustomField>
    <fullName>MPTimeout__c</fullName>
    <description>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</description>
    <inlineHelpText>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</inlineHelpText>
    <label>Time-out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/MPOrderCondition__c.object-meta.xml
<CustomObject>
    <label>Condiciones de Pedido</label>
    <nameField>
        <displayFormat>OC{00000}</displayFormat>
        <label>Order Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPOrderCondition__c/fields/MPAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de ajuste</label>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de cálculo</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPValue__c.field-meta.xml
<CustomField>
    <fullName>MPValue__c</fullName>
    <label>Valor negociado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo Lookup hacia el registro en el objeto MPIntegrationStatus__c el cual muestra un Log de las integraciones</description>
    <label>Detalle de la integración</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPQuoteCondition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPRentalObjectByStore__c/MPRentalObjectByStore__c.object-meta.xml
<CustomObject>
    <label>Objeto de Alquiler por Local</label>
    <nameField>
        <displayFormat>ROS-{000000}</displayFormat>
        <label>Rental Object By Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos de Alquiler por Local</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPRentalObjectByStore__c/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Objetos de Alquiler</relationshipLabel>
    <relationshipName>RentalObjectsByStore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MPExitDate__c.field-meta.xml
<CustomField>
    <fullName>MPExitDate__c</fullName>
    <description>Campo creado para tener la información de la fecha de entrega del local cuando hay una terminación de contrato</description>
    <label>Fecha de Salida</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/MPTermination.recordType-meta.xml
<RecordType>
    <fullName>MPTermination</fullName>
    <active>true</active>
    <label>Término</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>External Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractRescissionAPITest.cls
/**
 * @description       : 
 * @author            : Miller Mora
 * @group             : 
 * @last modified on  : 21-10-2024
 * @last modified by  : Miller Mora
**/
@IsTest
public class ContractRescissionAPITest {

    @TestSetup
    static void setupTestData() { 
    /**Crear pricebook (Condicion de contrato) */
        Pricebook2 contractType = Build.anPricebook2()
           .withName('Contrato Comercial Perú')
           .withMPPaymentCondition('MP12')
           .withMPIsProRataMethod(true)
           .withMPExternalCode('P101')
           .withIsActive(true)
           .withCurrencyIsoCode('PEN')
           .build();
        insert contractType;
        /**Fin pricebook (Condicion de contrato) */

        /**Crear tipos de negocio */
        MPBusinessType__c sector = Build.anMPSector()
           .withName('Burger Food')
           .withMPExternalCode('S-000001')
           .withMPCategory('Autoplaza')
           .withCurrencyIsoCode('PEN')
           .build();
        MPBusinessType__c businessUnit = Build.anMPBusinessUnit()
           .withName('Fast Food')
           .withMPExternalCode('B-000001')
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<MPBusinessType__c>{sector,businessUnit};
        /**Fin tipos de negocio */

        /**Crear cuentas */
        Account parentAcc = Build.anMPAccount()
           .withName('Parent Account')
           .withAccountCurrency('PEN')
           .build();
        insert parentAcc;

        Account brandAccount = Build.anBrandAccount()
           .withName('Brand Account 01')
           .withAccountCurrency('PEN')
           .withParentAccount(parentAcc)
           .withMPSector(sector)
           .build();
        Account mallAccount = Build.anMallAccount()
           .withName('Mall Account 01')
           .withAccountCurrency('PEN')
           .withMPExternalCode('PNO')
           .build();
        Account societyAccount = Build.anSocietyAccount()
           .withName('Society Account 01')
           .withAccountCurrency('PEN')
           .withMPExternalCode('1200')
           .build();
        insert new List<Account>{brandAccount, mallAccount, societyAccount} ;
        /**Fin crear cuentas */

        /**Crear locales y Objetos de alquiler */
        MPStore__c store = Build.anLocal()
           .withName('Local 1001')
           .withMPMall(mallAccount)
           .withMPFootage(100)
           .withMPExternalCode('store-0001')
           .withMPCeBe('cebe-001')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        MPStore__c rentalObject1 = Build.anMPRentalObject()
           .withName('OA 1001')
           .withMPMall(mallAccount)
           .withMPFootage(30)
           .withMPExternalCode('OA1001EXID')
           .withMPCeBe('')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        MPStore__c rentalObject2 = Build.anMPRentalObject()
           .withName('OA 1002')
           .withMPMall(mallAccount)
           .withMPFootage(30)
           .withMPExternalCode('OA1002EXID')
           .withMPCeBe('')
           .withMPBusinessUnit(businessUnit)
           .withCurrencyIsoCode('PEN')
           .withMPUsabilityStatus('Use')
           .withMPSociety(societyAccount)
           .withMPContractType(contractType)
           .build();
        insert new List<MPStore__c>{store,rentalObject1,rentalObject2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Objeto de Alquiler por local */
        MPRentalObjectByStore__c rentalObjectByStore1 = Build.anMPRentalObjectByStore()
           .withMPRentalObject(rentalObject1)
           .withMPStore(store)
           .build();
        MPRentalObjectByStore__c rentalObjectByStore2 = Build.anMPRentalObjectByStore()
           .withMPRentalObject(rentalObject2)
           .withMPStore(store)
           .build();
        insert new List<MPRentalObjectByStore__c>{rentalObjectByStore1,rentalObjectByStore2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Oportunidad */
        Opportunity opportunity1 = Build.anOpportunity()
           .withName('opportunity1')
           .withStageName('Exploración')
           .withAccount(parentAcc)
           .withMPBrand(brandAccount)
           .withMPMall(mallAccount)
           .withCloseDate((System.now().date()))
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<Opportunity>{opportunity1};
        /**Fin Oportunidad */

        /**Crear Quote */
        Quote quote1 = Build.anQuote()
           .withName('quote1')
           .withOpportunity(opportunity1)
           .withMPStore(store)
           .withStatus('Draft')
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<Quote>{quote1};
        /**Fin Quote */

        /**Crear Quote Condition */
        MPQuoteCondition__c quoteCondition1 = Build.anQuoteCondition()
           .withMPQuote(quote1)
           .withCurrencyIsoCode('PEN')
           .build();
        insert new List<MPQuoteCondition__c>{quoteCondition1};
        /**Fin Quote Quote Condition */

        // Crear orden y relacionarla con el contrato
        Order testOrder = Build.anOrder()
            .withAccount(parentAcc)
           // .withContract(testContract)
            .withStore(store)
            .withEffectiveDate(System.today())
            .withStatus('Draft')
            .withCurrencyIsoCode('PEN')
            .build();
        insert testOrder;

       
        // Crear objetos relacionados a la orden
        Product2 conditionClass = new Product2(Name='AP Fijo', MPExternalCode__c = 'AP30');
        insert conditionClass;

        MPCalculationRule__c calculationRule = new MPCalculationRule__c(Name='Arriendo Diciembre', MPExternalCode__c = 'MPAD');
        insert calculationRule;

        MPAdjustment__c adjustmentType = new MPAdjustment__c(Name='Adjustment Type A', MPPeriod__c = '2', MPValue__c = 10, MPExternalCode__c = 'MPAD2');
        insert adjustmentType;

        // Crear Order Condition y relacionarla con la orden
        MPOrderCondition__c orderCondition = Build.anOrderCondition()
            .withOrder(testOrder)
            .withConditionClass(conditionClass)
            .withCalculationRule(calculationRule)
            .withAdjustmentType(adjustmentType)
            .withStartDate(System.today())
            .withEndDate(System.today().addMonths(12))
            .withVolumenValue(100)
            .withValue(200)
            .withFinalVolumen(150)
            .withIntialVolumen(50)
            .build();
        insert orderCondition;
        
             // Crear contrato
        Contract testContract = Build.aContract()
            .withName('Test Class Contract')
            .withAccount(parentAcc)
            .withMall(mallAccount)
            .withMarca(brandAccount)
            .withCurrencyIsoCode('PEN')
            .withStartDate(System.today())
            .withEndDate(12) // 12 meses de duración
            .withStatus('Draft')
            .withOpp(opportunity1)
            .withOrder(testOrder)
            .withExternalCode('35083')
            .build();
        insert testContract;
        
         // Actualizar el contrato con la orden vigente
        testOrder.ContractId = testContract.Id;
        update testOrder;
        
        // Crear orden de terminacion y relacionarla con el contrato
        Order testOrderTermination = Build.anMPOrderTermination()
            .withAccount(parentAcc)
            .withContract(testContract)
            .withStore(store)
            .withEffectiveDate(System.today())
            .withStatus('Draft')
            .withStage('Activación de Término')
            .withCurrencyIsoCode('PEN')
            .build();
        insert testOrderTermination;
        
        testOrderTermination.MPExitDate__c = System.today().addDays(15);
        update testOrderTermination;
            
        MPIntegrationSetting__mdt integrationSetting = [SELECT DeveloperName, MPNamedCredential__c, MPApi_Path__c, MPTimeout__c, MPMaximumRetries__c, MPSecondsBetweenRetries__c FROM MPIntegrationSetting__mdt WHERE DeveloperName = 'MPContractRescission' LIMIT 1];
 
         // Crear integración status
        MPIntegrationStatus__c integrationStatus = Build.anMPIntegrationStatus()
            .withParentId(testOrderTermination.id)
            .withStatus('InProgress')
            .withMPIntegrationName(integrationSetting.DeveloperName)
            .build();
        insert new List<MPIntegrationStatus__c>{integrationStatus};    

    }
    
    @isTest
	static void testExecuteSuccess() {
        
        Integer httpCode = 200;
        
        Order objOrder = [SELECT Id FROM Order Where RecordType.DeveloperName = 'MPTermination'];
        MPIntegrationStatus__c integrationStatus = [SELECT Id,MPParentId__c FROM MPIntegrationStatus__c LIMIT 1];
        system.debug('integrationStatus::::::' + integrationStatus);
        
        String responseBody = '{ "closeDate": "2024-01-25","doCalculation": true,"doContractBlocking": true,"requester": {"fullName": "Bruno Rodrigues","email": "bruno.rodrigues@mallplaza.com"}}';
        
        Map<String, String> headerMap = new Map<String, String>();
        Test.setMock(HttpCalloutMock.class, new HttpMock(responseBody, httpCode, headerMap));
        ContractRescissionAPICallManager callManager = new ContractRescissionAPICallManager(objOrder, false, integrationStatus);
            
        Test.startTest();
        	Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        Test.stopTest();
        
        MPIntegrationStatus__c newIntegrationStatus = [SELECT Id, MPParentId__c, MPStatus__c, MPHttpCode__c FROM MPIntegrationStatus__c Where MPParentId__c =: objOrder.id LIMIT 1];
        System.debug(newIntegrationStatus);
        
        System.assertEquals(httpCode, newIntegrationStatus.MPHttpCode__c, 'La integración 4.5 no fue exitosa.');
       
    }
    
     @isTest
    static void testExecuteError() {
        
        Integer httpCode = 400;
        
        Order objOrder = [SELECT Id FROM Order Where RecordType.DeveloperName = 'MPTermination'];
        MPIntegrationStatus__c integrationStatus = [SELECT Id,MPParentId__c FROM MPIntegrationStatus__c LIMIT 1];
        system.debug('integrationStatus::::::' + integrationStatus);     
        
        String responseBody = '{"name": "parameters invalid",  "message": "Query value invalid."}';   
        Map<String, String> headerMap = new Map<String, String>(); 

        Test.setMock(HttpCalloutMock.class, new HttpMock(responseBody, httpCode, headerMap));
        ContractRescissionAPICallManager callManager = new ContractRescissionAPICallManager(objOrder, true, integrationStatus);
            
        Test.startTest();
        	Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        Test.stopTest();
                    
        Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
    }
    
     @isTest
    static void testInvokeFromFlow() {
        
        List<Order> lstOrders = [SELECT Id FROM Order Where RecordType.DeveloperName = 'MPTermination'];
        
        Test.startTest();
       	 ContractRescissionAPI_Inv.invokeFromFlowContractRescissionAPI(lstOrders);
        Test.stopTest();

        // Verificar que se creó el registro de MPIntegrationStatus__c
        MPIntegrationStatus__c integrationStatus = [SELECT Id FROM MPIntegrationStatus__c WHERE CreatedDate = TODAY LIMIT 1];
        System.assertNotEquals(null, integrationStatus, 'El registro de MPIntegrationStatus__c debe ser creado.');

        // Verificar que se encoló un trabajo Queueable
        List<AsyncApexJob> jobs = [SELECT Id, Status, JobType FROM AsyncApexJob WHERE JobType = 'Queueable' AND CreatedDate = TODAY];
        System.assert(!jobs.isEmpty(), 'Debería haberse encolado un trabajo Queueable.');
        System.assertEquals('Completed', jobs[0].Status, 'El trabajo Queueable debería haberse completado correctamente.');
    }

}