force-app/main/default/objects/Account/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>External Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPContractModificationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPContractModificationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles API Modificación de Contrato</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Contracts (Detalles API Modificación de Contrato)</relationshipLabel>
    <relationshipName>Contracts_MPContractModificationStatus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>En Proceso de Activación</fullName>
            </value>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Rescindido</fullName>
            </value>
            <value>
                <fullName>Terminado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPAdjustment__c/MPAdjustment__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado que permite generar ajustes en las clases de condición reajustables de acuerdo al tipo de contrato al que pertenecen.</description>
    <label>Ajuste</label>
    <nameField>
        <label>Nombre Ajuste</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ajustes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPAdjustment__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPBusinessType__c/MPBusinessType__c.object-meta.xml
<CustomObject>
    <label>Tipo de Negocio</label>
    <nameField>
        <label>Business Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Negocio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPCalculationRule__c/MPCalculationRule__c.object-meta.xml
<CustomObject>
    <label>Norma de Cálculo</label>
    <nameField>
        <label>Norma de Cálculo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Normas de Cálculo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/MPOrderCondition__c.object-meta.xml
<CustomObject>
    <label>Condiciones de Pedido</label>
    <nameField>
        <displayFormat>OC{00000}</displayFormat>
        <label>Order Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPOrderCondition__c/fields/MPAdjustment__c.field-meta.xml
<CustomField>
    <fullName>MPAdjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de ajuste</label>
    <referenceTo>MPAdjustment__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPOrderCondition__c/fields/MPCalculationRule__c.field-meta.xml
<CustomField>
    <fullName>MPCalculationRule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Norma de cálculo</label>
    <referenceTo>MPCalculationRule__c</referenceTo>
    <relationshipLabel>Condiciones de Pedidos</relationshipLabel>
    <relationshipName>Order_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo Lookup hacia el registro en el objeto MPIntegrationStatus__c el cual muestra un Log de las integraciones</description>
    <label>Detalle de la integración</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPQuoteCondition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPRentalObjectByStore__c/MPRentalObjectByStore__c.object-meta.xml
<CustomObject>
    <label>Objeto de Alquiler por Local</label>
    <nameField>
        <displayFormat>ROS-{000000}</displayFormat>
        <label>Rental Object By Store Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objetos de Alquiler por Local</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPRentalObjectByStore__c/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Objetos de Alquiler</relationshipLabel>
    <relationshipName>RentalObjectsByStore</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MPQuoteCondition__c.field-meta.xml
<CustomField>
    <fullName>MPQuoteCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Condiciones de Prespuesto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MPExternalCode__c.field-meta.xml
<CustomField>
    <fullName>MPExternalCode__c</fullName>
    <externalId>true</externalId>
    <label>External Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPStore__c.field-meta.xml
<CustomField>
    <fullName>MPStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>MPStore__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Local</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>MPStore__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>MPStoreQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractModificationAPITest.cls
/**
 * @description Clase de test para cumplir cobertura de clases relacionadas a la API de Modificación de contrato
 * @group Proyecto MP
 * @author Juan Felipe Muriel
 * @since 29-08-2024 - Creación
 */
@isTest
public with sharing class ContractModificationAPITest {
    @testSetup
    static void setup(){
        /**Crear pricebook (Condicion de contrato) */
        Pricebook2 contractType = Build.anPricebook2()
        .withName('Contrato Comercial Perú')
        .withMPPaymentCondition('MP12')
        .withMPIsProRataMethod(true)
        .withMPExternalCode('P101')
        .withIsActive(true)
        .withCurrencyIsoCode('PEN')
        .build();
        insert contractType;
        /**Fin pricebook (Condicion de contrato) */

        /**Crear tipos de negocio */
        MPBusinessType__c sector = Build.anMPSector()
        .withName('Burger Food')
        .withMPExternalCode('S-000001')
        .withMPCategory('Autoplaza')
        .withCurrencyIsoCode('PEN')
        .build();
        MPBusinessType__c businessUnit = Build.anMPBusinessUnit()
        .withName('Fast Food')
        .withMPExternalCode('B-000001')
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<MPBusinessType__c>{sector,businessUnit};
        /**Fin tipos de negocio */

        /**Crear cuentas */
        Account parentAcc = Build.anMPAccount()
        .withName('Parent Account')
        .withAccountCurrency('PEN')
        .build();
        insert parentAcc;

        Account brandAccount = Build.anBrandAccount()
        .withName('Brand Account 01')
        .withAccountCurrency('PEN')
        .withParentAccount(parentAcc)
        .withMPSector(sector)
        .build();
        Account mallAccount = Build.anMallAccount()
        .withName('Mall Account 01')
        .withAccountCurrency('PEN')
        .withMPExternalCode('PNO')
        .build();
        Account societyAccount = Build.anSocietyAccount()
        .withName('Society Account 01')
        .withAccountCurrency('PEN')
        .withMPExternalCode('1200')
        .build();
        insert new List<Account>{brandAccount, mallAccount, societyAccount} ;
        /**Fin crear cuentas */

        /**Crear locales y Objetos de alquiler */
        MPStore__c store = Build.anLocal()
        .withName('Local 1001')
        .withMPMall(mallAccount)
        .withMPFootage(100)
        .withMPExternalCode('store-0001')
        .withMPCeBe('cebe-001')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        MPStore__c rentalObject1 = Build.anMPRentalObject()
        .withName('OA 1001')
        .withMPMall(mallAccount)
        .withMPFootage(30)
        .withMPExternalCode('OA1001EXID')
        .withMPCeBe('')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        MPStore__c rentalObject2 = Build.anMPRentalObject()
        .withName('OA 1002')
        .withMPMall(mallAccount)
        .withMPFootage(30)
        .withMPExternalCode('OA1002EXID')
        .withMPCeBe('')
        .withMPBusinessUnit(businessUnit)
        .withCurrencyIsoCode('PEN')
        .withMPUsabilityStatus('Use')
        .withMPSociety(societyAccount)
        .withMPContractType(contractType)
        .build();
        insert new List<MPStore__c>{store,rentalObject1,rentalObject2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Objeto de Alquiler por local */
        MPRentalObjectByStore__c rentalObjectByStore1 = Build.anMPRentalObjectByStore()
        .withMPRentalObject(rentalObject1)
        .withMPStore(store)
        .build();
        MPRentalObjectByStore__c rentalObjectByStore2 = Build.anMPRentalObjectByStore()
        .withMPRentalObject(rentalObject2)
        .withMPStore(store)
        .build();
        insert new List<MPRentalObjectByStore__c>{rentalObjectByStore1,rentalObjectByStore2};
        /**Fin local y Objetos de alquiler*/

        /**Crear Oportunidad */
        Opportunity opportunity1 = Build.anOpportunity()
        .withName('opportunity1')
        .withStageName('Exploración')
        .withAccount(parentAcc)
        .withMPBrand(brandAccount)
        .withMPMall(mallAccount)
        .withCloseDate((System.now().date()))
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<Opportunity>{opportunity1};
        /**Fin Oportunidad */

        /**Crear Quote */
        Quote quote1 = Build.anQuote()
        .withName('quote1')
        .withOpportunity(opportunity1)
        .withMPStore(store)
        .withStatus('Draft')
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<Quote>{quote1};
        /**Fin Quote */

        /**Crear Quote Condition */
        MPQuoteCondition__c quoteCondition1 = Build.anQuoteCondition()
        .withMPQuote(quote1)
        .withCurrencyIsoCode('PEN')
        .build();
        insert new List<MPQuoteCondition__c>{quoteCondition1};
        /**Fin Quote Quote Condition */

        /**Crear orden */
        Order testOrder = Build.anOrder()
            .withAccount(parentAcc)
        // .withContract(testContract)
            .withStore(store)
            .withEffectiveDate(System.today())
            .withStatus('Draft')
            .withCurrencyIsoCode('PEN')
            .build();
        insert new List<Order>{testOrder};
        /**Fin orden */

        /** Crear Product2 */
        Product2 conditionClass = Build.anProduct2()
            .withIsActive(true)
            .withMPExternalCode('AP30')
            .withName('AP Fijo')
            .build();
        insert new List<Product2>{conditionClass};
        /** Fin Crear Product2 */

        /** Crear CalculationRule */
        MPCalculationRule__c calculationRule = Build.anCalculationRule()
            .withExternalCode('MPAD')
            .withName('MPAD')
            .build();
        insert new List<MPCalculationRule__c>{calculationRule};
        /** Fin Crear CalculationRule */

        /** Crear MPAdjustment__c */
        // MPAdjustment__c adjustmentType = Build.anStrategicAdjustment()
        //     .withPeriod('2')
        //     .withValue(10)
        //     .withExternalCode('MPAD2')
        //     .build();
        // insert new List<MPCalculationRule__c>{calculationRule};
        /** Fin Crear MPAdjustment__c */

        /** Crear MPOrderCondition__c */
        MPOrderCondition__c orderCondition = Build.anOrderCondition()
            .withOrder(testOrder)
            .withConditionClass(conditionClass)
            .withCalculationRule(calculationRule)
            // .withAdjustmentType(adjustmentType)
            .withStartDate(System.today())
            .withEndDate(System.today().addMonths(12))
            .withVolumenValue(100)
            .withValue(200)
            .withFinalVolumen(150)
            .withIntialVolumen(50)
            .build();
        insert new List<MPOrderCondition__c>{orderCondition};
        /** Fin Crear MPOrderCondition__c */

        /** Crear contrato */
        Contract testContract = Build.aContract()
            .withName('Test Class Contract')
            .withAccount(parentAcc)
            .withMall(mallAccount)
            .withMarca(brandAccount)
            .withCurrencyIsoCode('PEN')
            .withStartDate(System.today())
            .withEndDate(12) // 12 meses de duración
            .withStatus('Draft')
            .withOpp(opportunity1)
            .withOrder(testOrder)
            .withExternalCode('35083')
            .withRentalStartDate(System.now().date())
            .withProbableOpeningDate(System.now().date())
            .build();
        insert new List<Contract>{testContract};
        /** Fin Crear contrato */

        // Actualizar el contrato con la orden vigente
        testOrder.ContractId = testContract.Id;
        update testOrder;
    }

    @isTest
    static void testContractUpdate(){

        Integer httpCode = 200;
        String responseData = '{}';
        String contractExtCode = '35083';
        String integrationName = 'MPContractModificationAPI';
        String successValue = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');

        Boolean isReplyEnabled = false;
    
        Map<String, String> headerMap = new Map<String, String>();
    
        /** Obtener contrato a actualizar */
        Contract contract = [SELECT Id,name,ContractNumber,account.name FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
    
        /** Crear log de integracion */
        MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
        .withStatus(inProgress)
        .withParentId(contract.id)
        .withMPIntegrationName(integrationName)
        .build();
        insert newLog;

        Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
        ContractModificationAPICallManager callManager = new ContractModificationAPICallManager(contract,isReplyEnabled,newLog);
                
        Test.startTest();
        // Encolar y ejecutar el trabajo queueable
        Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        Test.stopTest();

        // Obtener registro actualizado
        Contract updatedContract = [SELECT Id, MPContractModificationStatus__c, MPContractModificationStatus__r.MPStatus__c FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
        System.debug(updatedContract.MPContractModificationStatus__c);

        Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
        Assert.isNotNull(updatedContract.MPContractModificationStatus__c, 'El campo Contract.MPContractModificationStatus__c no debe ser nulo');
        Assert.areEqual(successValue, updatedContract.MPContractModificationStatus__r.MPStatus__c, 'El estado debe ser: ' + successValue);
    }

    @isTest
    static void testHandleCallOutException(){

        Integer httpCode = 500;
        String responseData = '{}';
        String contractExtCode = '35083';
        String integrationName = 'MPContractModificationAPI';
        String successValue = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
        String errorValue = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        Boolean isReplyEnabled = false;
        Map<String, String> headerMap = new Map<String, String>();
    
        /** Obtener contrato a actualizar */
        Contract contract = [SELECT Id,name,ContractNumber,account.name FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
    
        /** Crear log de integracion */
        MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
        .withStatus(inProgress)
        .withParentId(contract.id)
        .withMPIntegrationName(integrationName)
        .build();
        insert newLog;

        Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
        ContractModificationAPICallManager callManager = new ContractModificationAPICallManager(contract,isReplyEnabled,newLog);
                
        Test.startTest();
        // Encolar y ejecutar el trabajo queueable
        Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        Test.stopTest();

        // Obtener registro actualizado
        Contract updatedContract = [SELECT Id, MPContractModificationStatus__c, MPContractModificationStatus__r.MPStatus__c, MPContractModificationStatus__r.MPHttpCode__c FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
        System.debug(updatedContract);

        Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
        Assert.isNotNull(updatedContract.MPContractModificationStatus__c, 'El campo Contract.MPContractModificationStatus__c no debe ser nulo');
        Assert.areEqual(errorValue, updatedContract.MPContractModificationStatus__r.MPStatus__c, 'El estado debe ser: ' + errorValue);
        Assert.areEqual(httpCode, updatedContract.MPContractModificationStatus__r.MPHttpCode__c, 'El estado HTTP debe ser: ' + httpCode);
    }

    @isTest
    static void testHandleCallOutExceptionRetries(){

        Integer httpCode = 500;
        String responseData = '{}';
        String contractExtCode = '35083';
        String integrationName = 'MPContractModificationAPI';
        String successValue = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
        String errorValue = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        Boolean isReplyEnabled = true;
        Map<String, String> headerMap = new Map<String, String>();
    
        /** Obtener contrato a actualizar */
        Contract contract = [SELECT Id,name,ContractNumber,account.name FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
    
        /** Crear log de integracion */
        MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
        .withStatus(inProgress)
        .withParentId(contract.id)
        .withMPIntegrationName(integrationName)
        .build();
        insert newLog;

        Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
        ContractModificationAPICallManager callManager = new ContractModificationAPICallManager(contract,isReplyEnabled,newLog);
                
        Test.startTest();
        // Encolar y ejecutar el trabajo queueable
        Id jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        Test.stopTest();

        // Obtener registro actualizado
        Contract updatedContract = [SELECT Id, MPContractModificationStatus__c, MPContractModificationStatus__r.MPStatus__c, MPContractModificationStatus__r.MPHttpCode__c FROM Contract WHERE MPExternalCode__c =: contractExtCode LIMIT 1];
        System.debug(updatedContract);

        Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
        Assert.isNotNull(updatedContract.MPContractModificationStatus__c, 'El campo Contract.MPContractModificationStatus__c no debe ser nulo');
        Assert.areEqual(errorValue, updatedContract.MPContractModificationStatus__r.MPStatus__c, 'El estado debe ser: ' + errorValue);
        Assert.areEqual(httpCode, updatedContract.MPContractModificationStatus__r.MPHttpCode__c, 'El estado HTTP debe ser: ' + httpCode);
    }

    // @isTest
    // static void testHandleSalesforceException(){
        // /** Provocaremos una excepción enviando un contrato Nulo, a pesar de que el endpoint responda 200 */
        // Integer httpCode = 200;
        // String responseData = '{}';
        // String contractExtCode = '35083';
        // String integrationName = 'MPContractModificationAPI';
        // String successValue = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        // String inProgress = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
        // String errorValue = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        // Boolean isReplyEnabled = true;
        // Map<String, String> headerMap = new Map<String, String>();
    
        // /** Obtener contrato a actualizar */
        // Contract contract = null;
    
        // /** Crear log de integracion */
        // MPIntegrationStatus__c newLog = Build.anMPIntegrationStatus()
        // .withStatus(inProgress)
        // .withParentId(null)
        // .withMPIntegrationName(integrationName)
        // .build();
        // insert newLog;

        // Test.setMock(HttpCalloutMock.class, new HttpMock(responseData, httpCode, headerMap));
        // ContractModificationAPICallManager callManager = new ContractModificationAPICallManager(contract,isReplyEnabled,newLog);
                
        // Test.startTest();
        // Id jobId;
        // try {
        //     // Encolar y ejecutar el trabajo queueable
        //     jobId = System.enqueueJob(new CallManagerQueueable(callManager));
        // } catch (Exception e) {
        //     System.debug('Hubo una excepcion : ' + e.getMessage() );
        // }
        // Test.stopTest();

        // // Obtener registro de Log
        // // MPIntegrationStatus__c updatedLog = [SELECT Id, MPStatus__c,MPSalesforceException__c FROM MPIntegrationStatus__c WHERE Id =: newLog.Id LIMIT 1];

        // Assert.isNotNull(jobId, 'El Job ID no debería ser nulo después de encolar el trabajo.');
        // // Assert.isNotNull(updatedLog.MPSalesforceException__c, 'El capo MPIntegrationStatus__c.MPSalesforceException__c no debería ser nulo.');
        // // Assert.areEqual(errorValue, updatedLog.MPStatus__c, 'El estado debe ser: ' + errorValue);
    // }
}