force-app/main/default/objects/Account/fields/MPIdentificationNumber__c.field-meta.xml
<CustomField>
    <fullName>MPIdentificationNumber__c</fullName>
    <label>Número de Identificación</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/MPSociety.recordType-meta.xml
<RecordType>
    <fullName>MPSociety</fullName>
    <active>true</active>
    <description>Tipo de registro que permite capturar la información de las sociedades propietarias de locales.</description>
    <label>Sociedad</label>
</RecordType>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendRecordEventTest.cls
@isTest
public class SendRecordEventTest {
    @TestSetup
    static void setup() {

        Id societyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('MPSociety').getRecordTypeId();

        Account testAccount = new Account();
        testAccount.RecordTypeId = societyRecordTypeId;
        testAccount.Name = 'Society Account';
        testAccount.CurrencyIsoCode = 'PEN';
        testAccount.MPIdentificationNumber__c = '12345123451234512345';
        insert testAccount;        
    }

    @isTest
    static void sendRecordsCallout() {

        // get account fields to query
        List<String> fieldsList = Utilities_cls.getAllFields('Account');
        String fieldsToQuery = Utilities_cls.getQueryFields(fieldsList);
        // query a random account
        List<Account> testAccountList = Database.query('SELECT ' + fieldsToQuery + ' FROM Account');
        // create flow output variables
        List<SendRecordEventService.FlowInput> flowInputList = new List<SendRecordEventService.FlowInput>();
        SendRecordEventService.FlowInput flowInput = new SendRecordEventService.FlowInput();
        Account testAccount = testAccountList.get(0);
        flowInput.accountToSend = testAccountList;
        flowInput.objectName = 'Account';
        flowInput.operationType = 'CREATE';
        flowInputList.add(flowInput);

        Test.setMock(HttpCalloutMock.class, new SendRecordEventHttpMock());
        Test.startTest();
        SendRecordEventService.sendRecords(flowInputList);
        Test.stopTest();

        MPIntegrationStatus__c integrationLog = [SELECT Id, 
                                                        MPStatus__c, 
                                                        MPParentId__c
                                                    FROM MPIntegrationStatus__c
                                                    WHERE MPStatus__c = 'SUCCESS'
                                                    AND MPIntegrationName__c = 'Integracion Eventos Cuentas'
                                                    AND MPParentId__c = :testAccount.Id LIMIT 1];
        Assert.areEqual(testAccount.Id, integrationLog.MPParentId__c);
                                                    
    }
}