force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path_2__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path_2__c</fullName>
    <description>Es un path adicioinal. Para concaterse en la URL</description>
    <label>Api Path 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path__c</fullName>
    <description>Ruta de la API, despues de su raíz.</description>
    <label>Api Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMaximumRetries__c.field-meta.xml
<CustomField>
    <fullName>MPMaximumRetries__c</fullName>
    <description>Numero máximo de re-intentos permitidos.</description>
    <inlineHelpText>Numero máximo de re-intentos permitidos.</inlineHelpText>
    <label>Número máximo de reintentos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPNamedCredential__c.field-meta.xml
<CustomField>
    <fullName>MPNamedCredential__c</fullName>
    <description>Api name del Named Credential que se utiliza en la integración.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPTimeout__c.field-meta.xml
<CustomField>
    <fullName>MPTimeout__c</fullName>
    <description>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</description>
    <inlineHelpText>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</inlineHelpText>
    <label>Time-out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPStore__c/MPStore__c.object-meta.xml
<CustomObject>
    <label>Local</label>
    <nameField>
        <label>Local Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPStore__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendRecordEventService.cls
public with sharing class SendRecordEventService {

    @InvocableMethod
    public static void sendRecords(List<FlowInput> flowInput) {

        List<Object> objectList = new List<Object>();
        String recordId;
        if (flowInput[0].objectName.equalsIgnoreCase('Account')) {
            recordId = flowInput[0].accountToSend[0].Id.toString();
            objectList.addAll(flowInput[0].accountToSend);
        } else if (flowInput[0].objectName.equalsIgnoreCase('Contact')) {
            recordId = flowInput[0].contactToSend[0].Id.toString();
            objectList.addAll(flowInput[0].contactToSend);
        } else if (flowInput[0].objectName.equalsIgnoreCase('Store')) {
            recordId = flowInput[0].storeToSend[0].Id.toString();
            objectList.addAll(flowInput[0].storeToSend);
        }
         
        // get object name for api path purposes
        String objectName = flowInput[0].objectName;
        String customMetadataName = 'MPEvents' + objectName;
        final String NAMED_CREDENTIAL = MPIntegrationSetting__mdt.getInstance(customMetadataName).MPNamedCredential__c;
        final String API_PATH = MPIntegrationSetting__mdt.getInstance(customMetadataName).MPApi_Path__c;
        final String API_PATH_2 = MPIntegrationSetting__mdt.getInstance(customMetadataName).MPApi_Path_2__c;
        final Integer TIME_OUT = (Integer) MPIntegrationSetting__mdt.getInstance(customMetadataName).MPTimeout__c;
        final Integer MAX_RETRIES = (Integer) MPIntegrationSetting__mdt.getInstance(customMetadataName).MPMaximumRetries__c;
        final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance(customMetadataName).Masterlabel;
        final String HTTP_METHOD_POST = 'POST';
        // request maps
        List<Map<String, Object>> messages = new List<Map<String, Object>>();
        Map<String, Object> messageData = new Map<String, Object>();                           
        Map<String, Object> message = new Map<String, Object>();
        Map<String, Object> jsonAttributes = new Map<String, Object>();       
        // request building 
        message.put('data', objectList.get(0));            
        jsonAttributes.put('EVENT_ID', UUID.randomUUID());
        jsonAttributes.put('EVENT_TYPE', flowInput[0].operationType);
        jsonAttributes.put('ENTITY_ID', flowInput[0].objectName);
        jsonAttributes.put('ENTITY_TYPE', flowInput[0].objectName);
        jsonAttributes.put('DATE_TIME', Datetime.now());
        jsonAttributes.put('VERSION', '1.0');
        jsonAttributes.put('COUNTRY', 'PE');
        jsonAttributes.put('COMMERCE', 'mallplaza');
        jsonAttributes.put('CHANNEL', 'salesforce');
        jsonAttributes.put('DOMAIN_ID', 'REMA');
        jsonAttributes.put('CAPABILITY', 'POMA');
        jsonAttributes.put('MIME_TYPE',  'application/json');
        message.put('attributes', jsonAttributes);        
        messages.add(message);
        messageData.put('messages', messages);
        String jsonBody = JSON.serialize(messageData);           

        if (objectList.size() == 1) {
            sendRecordsCallout(NAMED_CREDENTIAL, 
                                INTEGRATION_NAME, 
                                API_PATH, 
                                API_PATH_2, 
                                TIME_OUT, 
                                HTTP_METHOD_POST, 
                                MAX_RETRIES, 
                                jsonBody, 
                                recordId);
        }
    }

    @future(callout=true)
    public static void sendRecordsCallout(String NamedCredential,
                                            String integrationName, 
                                            String apipath, 
                                            String apipath2, 
                                            Integer timeOut,
                                            String httpMethod, 
                                            Integer maxRetries,
                                            String jsonBody, 
                                            String recordId
                                            ) {
        
        MPIntegrationStatus__c integrationLog = new MPIntegrationStatus__c();
        integrationLog.MPRequestDateTime__c = System.now();
        try {
            // request
            System.debug('REQUEST ---> ' + jsonBody);
            HttpRequest request = new HttpRequest();
            request.setEndpoint('callout:' + NamedCredential + apipath + apipath2);
            request.setBody(jsonBody);
            request.setHeader('Content-Type', 'application/json');
            request.setMethod(httpMethod);
            request.setTimeout(timeOut);
            // response
            Http http = new Http();
            HTTPResponse response = http.send(request);
            System.debug('RESPONSE ---> ' + response.getBody());
            // set integration log
            integrationLog.MPIntegrationName__c = integrationName;
            integrationLog.MPRequest__c = jsonBody;
            integrationLog.MPResponse__c = response.getBody();
            integrationLog.MPHttpCode__c = response.getStatusCode();
            integrationLog.MPStatus__c = response.getStatusCode() == 200 ? 'Success' : 'Error'; 
            integrationLog.MPSalesforceException__c = response.getStatusCode() == 200 ? '' : response.getStatus();
            integrationLog.MPResponseDateTime__c = System.now();
            integrationLog.MPParentId__c = recordId;
            insert integrationLog;
        } catch (Exception e) {
            integrationLog.MPStatus__c = 'Error';
            integrationLog.MPSalesforceException__c = e.getMessage();
            integrationLog.MPResponseDateTime__c = System.now();
            System.debug('Error message: ' + e.getMessage());
            integrationLog.MPParentId__c = recordId;
            insert integrationLog;
        }        
    }

    public class FlowInput {
        @InvocableVariable
        public String operationType;

        @InvocableVariable
        public String objectName;

        public Object recordToSend;

        @InvocableVariable
        public List<Account> accountToSend;

        @InvocableVariable
        public List<Contact> contactToSend;

        @InvocableVariable
        public List<MPStore__c> storeToSend;
    }
}