force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path_2__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path_2__c</fullName>
    <description>Es un path adicioinal. Para concaterse en la URL</description>
    <label>Api Path 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path__c</fullName>
    <description>Ruta de la API, despues de su raíz.</description>
    <label>Api Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMethod__c.field-meta.xml
<CustomField>
    <fullName>MPMethod__c</fullName>
    <label>Método</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPNamedCredential__c.field-meta.xml
<CustomField>
    <fullName>MPNamedCredential__c</fullName>
    <description>Api name del Named Credential que se utiliza en la integración.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPSuccessfulHttpCodes__c.field-meta.xml
<CustomField>
    <fullName>MPSuccessfulHttpCodes__c</fullName>
    <description>Lista de códigos http que se deben tomar como éxito. Separe los códigos con punto y coma. Ejemplo: &apos;200;201&apos;</description>
    <inlineHelpText>Lista de códigos http que se deben tomar como éxito. Separe los códigos con punto y coma. Ejemplo: &apos;200;201&apos;</inlineHelpText>
    <label>Códigos http exitosos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPTimeout__c.field-meta.xml
<CustomField>
    <fullName>MPTimeout__c</fullName>
    <description>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</description>
    <inlineHelpText>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</inlineHelpText>
    <label>Time-out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgreementContRescAPICallOutService.cls
/**
 * @description Clase encargada de hacer la llamada a la API 4.8 Termino de Contrato Acuerdo.
 * @group Proyecto MP
 * @author Miller
 * @since 22810-2024 - Creación
 */
public with sharing class AgreementContRescAPICallOutService {

    /** Códigos HTTP de exito */
    public static final String SUCCESSFUL_HTTP_CODES = MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPSuccessfulHttpCodes__c;
    /** Método HTTP */
    public static final String HTTP_METHOD = MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPMethod__c;
    /** API name del Named Credential creado en Salesforce, el cual tiene parametrizado las credenciales de autenticación, encabezados y la URL Raiz de la API a consumir */
    public static final String  NAMED_CREDENTIAL = MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPNamedCredential__c;
    /** Ruta especifica para acceder a la API */
    public static final String  API_PATH = MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPApi_Path__c;
    /** Tiempo máximo de espera para una respuesta de la API */
    public static final Integer TIME_OUT = (Integer) MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPTimeout__c;
    /** Signo '/' */
    public static final String SLASH = '/';
    /** Path adicioinal */
    public static final String API_PATH_ADICIONAL = MPIntegrationSetting__mdt.getInstance('MPAgreementContRescission').MPApi_Path_2__c;

    public static AgreementContRescissionAPIWrapper makeCallout(AgreementContRescissionAPIWrapper agreementContRescissionAPIWrapper) {

       agreementContRescissionAPIWrapper.requestDateTime = System.now();
       String params = agreementContRescissionAPIWrapper.params.companyCode + SLASH + agreementContRescissionAPIWrapper.params.contractId + SLASH;
       List<Integer> successfulCodes = Utilities_cls.getSuccessfulHttpCodes(SUCCESSFUL_HTTP_CODES);

       HttpRequest request;
       HTTPResponse response;

       try {
           request = new HttpRequest();
           request.setEndpoint('callout:' + NAMED_CREDENTIAL + API_PATH + params + API_PATH_ADICIONAL );
           System.debug('request.setEndpoint: ' + NAMED_CREDENTIAL + API_PATH + params + API_PATH_ADICIONAL);
           String requestBody = JSON.serialize(agreementContRescissionAPIWrapper.request);
           System.debug('Cuerpo de la solicitud: ' + requestBody);
           request.setBody(requestBody);
           request.setMethod(HTTP_METHOD);
           request.setTimeout(TIME_OUT);

           Http http = new Http();
           response = http.send(request);

           System.debug('Código de estado de la respuesta: ' + response.getStatusCode());
           System.debug('Cuerpo de la respuesta: ' + response.getBody());

           if (successfulCodes.contains(response.getStatusCode())) {
               System.debug('LLAMADA CORRECTA');
               AgreementContRescissionAPIWrapper = handleSuccess(AgreementContRescissionAPIWrapper, response);
           }else{
               System.debug('LLAMADA INCORRECTA - Código de estado: ' + response.getStatusCode());
               throw new CalloutException(response.getBody());
           }
       }catch (Exception e) {
           System.debug('Excepción general: ' + e.getMessage());
           if (response != null) {
               System.debug('Código de estado HTTP: ' + response.getStatusCode());
               System.debug('Cuerpo de la respuesta: ' + response.getBody());
           } else {
               System.debug('No se recibió respuesta del servidor');
           }
           agreementContRescissionAPIWrapper = handleError(agreementContRescissionAPIWrapper, e, response);
       }

       return agreementContRescissionAPIWrapper;

   }

   
   private static AgreementContRescissionAPIWrapper handleSuccess(AgreementContRescissionAPIWrapper agreementContRescissionAPIWrapper, HTTPResponse response){
       if(response != null){
           agreementContRescissionAPIWrapper.response.message = response.getBody();
           agreementContRescissionAPIWrapper.httpCode = response.getStatusCode();
       }
       agreementContRescissionAPIWrapper.status = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
       agreementContRescissionAPIWrapper.responseDateTime = System.now();
       return agreementContRescissionAPIWrapper;
   }


   private static AgreementContRescissionAPIWrapper handleError(AgreementContRescissionAPIWrapper agreementContRescissionAPIWrapper, Exception e, HTTPResponse response){
       if(response != null){
           agreementContRescissionAPIWrapper.httpCode = response.getStatusCode();
       }
       agreementContRescissionAPIWrapper.responseDateTime = System.now();
       agreementContRescissionAPIWrapper.status = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
       agreementContRescissionAPIWrapper.response.message = e.getMessage();
       return agreementContRescissionAPIWrapper;
   }
   
}