force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path_2__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path_2__c</fullName>
    <description>Es un path adicioinal. Para concaterse en la URL</description>
    <label>Api Path 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path__c</fullName>
    <description>Ruta de la API, despues de su raíz.</description>
    <label>Api Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMethod__c.field-meta.xml
<CustomField>
    <fullName>MPMethod__c</fullName>
    <label>Método</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPNamedCredential__c.field-meta.xml
<CustomField>
    <fullName>MPNamedCredential__c</fullName>
    <description>Api name del Named Credential que se utiliza en la integración.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPSuccessfulHttpCodes__c.field-meta.xml
<CustomField>
    <fullName>MPSuccessfulHttpCodes__c</fullName>
    <description>Lista de códigos http que se deben tomar como éxito. Separe los códigos con punto y coma. Ejemplo: &apos;200;201&apos;</description>
    <inlineHelpText>Lista de códigos http que se deben tomar como éxito. Separe los códigos con punto y coma. Ejemplo: &apos;200;201&apos;</inlineHelpText>
    <label>Códigos http exitosos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPTimeout__c.field-meta.xml
<CustomField>
    <fullName>MPTimeout__c</fullName>
    <description>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</description>
    <inlineHelpText>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</inlineHelpText>
    <label>Time-out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractDatesUpdateAPICallOutService.cls
/**
 * @description Clase encargada de hacer la llamada a la API de Actualizacion de fechas de contrato.
 * @group Proyecto MP
 * @author Juan Felipe Muriel
 * @since 20-08-2024 - Creación
 */
public with sharing class ContractDatesUpdateAPICallOutService {
    /** Códigos HTTP de exito */
    public static final String SUCCESSFUL_HTTP_CODES = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPSuccessfulHttpCodes__c;
    /** Método HTTP */
    public static final String HTTP_METHOD = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPMethod__c;
    /** API name del Named Credential creado en Salesforce, el cual tiene parametrizado las credenciales de autenticación, encabezados y la URL Raiz de la API a consumir */
    public static final String  NAMED_CREDENTIAL = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPNamedCredential__c;
    /** Ruta especifica para acceder a la API */
    public static final String  API_PATH = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPApi_Path__c;
    /** Tiempo máximo de espera para una respuesta de la API */
    public static final Integer TIME_OUT = (Integer) MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPTimeout__c;
    /** Signo '/' */
    public static final String SLASH = '/';
    /** Path adicioinal */
    public static final String API_PATH_ADICIONAL = MPIntegrationSetting__mdt.getInstance('MPContractDatesUpdate').MPApi_Path_2__c;

    public static ContractDatesUpdateAPIWrapper makeCallout(ContractDatesUpdateAPIWrapper contractDatesWrapper) {
        contractDatesWrapper.requestDateTime = System.now();
        String params = contractDatesWrapper.params.companyCode + SLASH + contractDatesWrapper.params.contractId + SLASH;
        List<Integer> successfulCodes = Utilities_cls.getSuccessfulHttpCodes(SUCCESSFUL_HTTP_CODES);

        HTTPResponse response;
        HttpRequest request;

        try {
            request = new HttpRequest();
            request.setEndpoint('callout:' + NAMED_CREDENTIAL + API_PATH + params + API_PATH_ADICIONAL);
            request.setBody(JSON.serialize(contractDatesWrapper.request));
            request.setMethod(HTTP_METHOD);
            request.setTimeout(TIME_OUT);

            Http http = new Http();
            response = http.send(request);
    
            if (successfulCodes.contains(response.getStatusCode())) {
                System.debug('LLAMADA CORRECTA');
                contractDatesWrapper = handleSuccess(contractDatesWrapper, response);
            }else{
                System.debug('LLAMADA INCORRECTA');
                throw new CalloutException(response.getBody());
            }
        }catch (Exception e) {
            System.debug('Excepción general: ' + e.getMessage());
            contractDatesWrapper = handleError(contractDatesWrapper, e, response);
        }
        return contractDatesWrapper;
    }

    /**
    * @description Método encargado de devolver la respuesta exitosa de la API.
    * @author Juan Felipe Muriel | 20-08-2024
    * @param contractDatesWrapper Clase Wrapper que contiene datos de la llamada a la API.
    * @param response Respuesta de la API.
    * @return contractDatesWrapper Respuesta de la API de precios en el formato del objeto ContractDatesUpdateAPIWrapper.
    **/
    private static ContractDatesUpdateAPIWrapper handleSuccess(ContractDatesUpdateAPIWrapper contractDatesWrapper, HTTPResponse response){
        if(response != null){
            contractDatesWrapper.response.message = response.getBody();
            contractDatesWrapper.httpCode = response.getStatusCode();
        }
        contractDatesWrapper.status = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        contractDatesWrapper.responseDateTime = System.now();
        return contractDatesWrapper;
    }

    /**
    * @description Método encargado de devolver la respuesta fallida de la API.
    * @author Juan Felipe Muriel | 20-08-2024
    * @param contractDatesWrapper Clase Wrapper que contiene datos de la llamada a la API.
    * @param e Excepción capturada al momento de hacer la llamada a la API.
    * @param response Respuesta de la API.
    * @return contractDatesWrapper Respuesta de la API de precios en el formato del objeto ContractDatesUpdateAPIWrapper.
    **/
    private static ContractDatesUpdateAPIWrapper handleError(ContractDatesUpdateAPIWrapper contractDatesWrapper, Exception e, HTTPResponse response){
        if(response != null){
            contractDatesWrapper.httpCode = response.getStatusCode();
        }
        contractDatesWrapper.responseDateTime = System.now();
        contractDatesWrapper.status = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        contractDatesWrapper.response.message = e.getMessage();
        return contractDatesWrapper;
    }
}