force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPApi_Path__c.field-meta.xml
<CustomField>
    <fullName>MPApi_Path__c</fullName>
    <description>Ruta de la API, despues de su raíz.</description>
    <label>Api Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPMethod__c.field-meta.xml
<CustomField>
    <fullName>MPMethod__c</fullName>
    <label>Método</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPNamedCredential__c.field-meta.xml
<CustomField>
    <fullName>MPNamedCredential__c</fullName>
    <description>Api name del Named Credential que se utiliza en la integración.</description>
    <label>Named Credential</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPTimeout__c.field-meta.xml
<CustomField>
    <fullName>MPTimeout__c</fullName>
    <description>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</description>
    <inlineHelpText>Tiempo maximo de respuesta de una petición. Valor en Milisegundos.</inlineHelpText>
    <label>Time-out</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetContractAPICallOutService.cls
public with sharing class GetContractAPICallOutService {
   /** Códigos HTTP de exito */
   public static final Integer SUCCESSFUL_HTTP_CODES = 200;
   /** Método HTTP */
   public static final String HTTP_METHOD = MPIntegrationSetting__mdt.getInstance('MPGETContract').MPMethod__c;
   /** API name del Named Credential creado en Salesforce, el cual tiene parametrizado las credenciales de autenticación, encabezados y la URL Raiz de la API a consumir */
   public static final String  NAMED_CREDENTIAL = MPIntegrationSetting__mdt.getInstance('MPGETContract').MPNamedCredential__c;
   /** Ruta especifica para acceder a la API */
   public static final String  API_PATH = MPIntegrationSetting__mdt.getInstance('MPGETContract').MPApi_Path__c;
   /** Tiempo máximo de espera para una respuesta de la API */
   public static final Integer TIME_OUT = (Integer) MPIntegrationSetting__mdt.getInstance('MPGETContract').MPTimeout__c;
   /** Signo '/' */
   public static final String SLASH = '/';

   public static GetContractAPIWrapper makeCallout(GetContractAPIWrapper getContractAPIWrapper) {

        getContractAPIWrapper.requestDateTime = System.now();
        String params = getContractAPIWrapper.params.companyCode + SLASH + getContractAPIWrapper.params.contractId + SLASH;
        HttpRequest request;
        HTTPResponse response;

        try {
            request = new HttpRequest();
            request.setEndpoint('callout:' + NAMED_CREDENTIAL + API_PATH + params );
            System.debug('request.setEndpoint: ' + NAMED_CREDENTIAL + API_PATH + params);
            request.setMethod(HTTP_METHOD);
            request.setTimeout(TIME_OUT);

            Http http = new Http();
            response = http.send(request);

            if (response.getStatusCode() == SUCCESSFUL_HTTP_CODES) {
                System.debug('LLAMADA CORRECTA');
                getContractAPIWrapper = handleSuccess(getContractAPIWrapper, response);
            }else{
                System.debug('LLAMADA INCORRECTA');
                throw new CalloutException(response.getBody());
            }
        }catch (Exception e) {
            System.debug('Excepción general: ' + e.getMessage());
            getContractAPIWrapper = handleError(getContractAPIWrapper, e, response);
        }

        return getContractAPIWrapper;

    }


    private static GetContractAPIWrapper handleSuccess(GetContractAPIWrapper getContractAPIWrapper, HTTPResponse response){
        if(response != null){
            getContractAPIWrapper.response.message = response.getBody();
            getContractAPIWrapper.httpCode = response.getStatusCode();
        }
        getContractAPIWrapper.status = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');
        getContractAPIWrapper.responseDateTime = System.now();
        return getContractAPIWrapper;
    }


    private static GetContractAPIWrapper handleError(GetContractAPIWrapper getContractAPIWrapper, Exception e, HTTPResponse response){
        if(response != null){
            getContractAPIWrapper.httpCode = response.getStatusCode();
        }
        getContractAPIWrapper.responseDateTime = System.now();
        getContractAPIWrapper.status = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
        getContractAPIWrapper.response.message = e.getMessage();
        return getContractAPIWrapper;
    }




}