force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPRetry__c.field-meta.xml
<CustomField>
    <fullName>MPRetry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permitir o no re-intentos.</description>
    <inlineHelpText>Permitir o no re-intentos.</inlineHelpText>
    <label>Habilitar reintentos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancellationContrRescAPI_Inv.cls
/**
 * @description Clase tipo invocable que llama la clase manager de la intergracion 4.6 de Cancelación Termino Contrato
 * @group Proyecto MP
 * @author Miller Mora
 * @since 29-10-2024 - Creación
 */
public with sharing class CancellationContrRescAPI_Inv {

     /** Estado inicial de la integración */
     private static final String IN_PROGRESS_STATUS = Utilities_cls.getInProgressValue('MPIntegrationStatus__c', 'MPStatus__c');
     /** Nombre de la integración */
     public static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPCancellationContractRescission').DeveloperName;
     /** Número máximo de reintentos a la API */
     public static final Boolean RETRY = MPIntegrationSetting__mdt.getInstance('MPCancellationContractRescission').MPRetry__c;
 
     /**
      * @description Método invocable para ser llamado desde un Flow.
      * Este método encola un trabajo Queueable que ejecutará la lógica del CancellationContrRescAPICallManager.
      * @author Miller Mora | 29-08-2024 
      * @param OrderIds List<Id> - Lista de IDs de las ordenes que serán procesadas.
      */
     @InvocableMethod(label='Invoke Call Manager from Flow CancellationContrRescAPI' description='Invokes the Call Manager Queueable from Flow')
     public static void invokeFromFlowCancellationContrRescAPI(List<Order> lstorders) {
 
         Order orderRescission = lstorders[NumbersEnum.CERO.ordinal()];
         if(orderRescission != null){
             // Creación del log de integración
             MPIntegrationStatus__c intStatus = getIntStatus(orderRescission.Id);
             insert intStatus;
 
             System.debug('intStatus intStatus' + intStatus.MPStatus__c);
             // Ejecutar integración
             CancellationContrRescAPICallManager callManager = new CancellationContrRescAPICallManager(orderRescission,RETRY,intStatus);
             System.enqueueJob(new CallManagerQueueable(callManager));
         }
 
    }
 
 
     /**
      * @description Método encargado de crear una nueva instancia del objeto 'MPIntegrationStatus__c'
      * @author Miller Mora | 29-08-2024 
      * @param orderId Id de la Orden
      * @return Nueva instancia de 'MPIntegrationStatus__c'
      */
     private static MPIntegrationStatus__c getIntStatus(Id orderId) {
         MPIntegrationStatus__c newLog = new MPIntegrationStatus__c();
         newLog.MPIntegrationName__c    = INTEGRATION_NAME;
         newLog.MPParentId__c           = String.valueOf(orderId);
         newLog.MPStatus__c             = IN_PROGRESS_STATUS;
         return newLog;
     }

}