force-app/main/default/objects/MPIntegrationSetting__mdt/fields/MPRetry__c.field-meta.xml
<CustomField>
    <fullName>MPRetry__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permitir o no re-intentos.</description>
    <inlineHelpText>Permitir o no re-intentos.</inlineHelpText>
    <label>Habilitar reintentos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/MPQuoteCondition__c.object-meta.xml
<CustomObject>
    <label>Condición de Presupuesto</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Condición de Presupuesto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condiciones de Presupuesto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo Lookup hacia el registro en el objeto MPIntegrationStatus__c el cual muestra un Log de las integraciones</description>
    <label>Detalle de la integración</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Condiciones de Presupuesto</relationshipLabel>
    <relationshipName>MPQuoteCondition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPPricingApiStatus__c.field-meta.xml
<CustomField>
    <fullName>MPPricingApiStatus__c</fullName>
    <description>Estado de la Integración de Precios.</description>
    <inlineHelpText>Estado de la Integración de Precios.</inlineHelpText>
    <label>Estado API Precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPQuoteCondition__c/fields/MPQuote__c.field-meta.xml
<CustomField>
    <fullName>MPQuote__c</fullName>
    <label>Presupuesto</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>QuoteConditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MPPricingApiStatus__c.field-meta.xml
<CustomField>
    <fullName>MPPricingApiStatus__c</fullName>
    <description>Estado de la integración de precios de un registro de Condiciones de presupuesto asociado el cual necesita el valor sugerido provendiente de una API de precios.</description>
    <inlineHelpText>Estado de la integración de precios de un registro de Condiciones de presupuesto asociado el cual necesita el valor sugerido provendiente de una API de precios.</inlineHelpText>
    <label>Estado API Precios</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PricingAPI_inv.cls
/**
 * @description Clase usada en Trigger Flow de MPQuoteCondition__c para invocar la integración de precios.
 * @group Proyecto MP
 * @author Marco Guevara (MG)
 * @since 05-08-2024 - Creación
 */
public with sharing class PricingAPI_inv {

    public static final String IN_PROGRESS_STATUS = Utilities_cls.getInprogressValue('MPQuoteCondition__c', 'MPPricingApiStatus__c');
    public static final Boolean IS_RETRY_ENABLED = MPIntegrationSetting__mdt.getInstance('MPPricing').MPRetry__c;// Obtener valor por defecto si se deben hacer reintentos
    private static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPPricing').DeveloperName;

    /**
     * @description Método encargado de ejecutar la integración de precios.
     * @author Juan Felipe Muriel | 05-08-2024 
     * @param lstMPQuoteCondition Lista de condicioines de presupuesto filtradas las cuales deben obtener el valor
     * sugerido desde la API de precios.
     */
    @InvocableMethod(label='Call the Pricing API' description='Call the Pricing API in order to obtain the suggested value for the condition class' category='Quote Condition')
    public static void callPricingAPI(List<MPQuoteCondition__c> lstMPQuoteCondition) {   
        Set<Id> quoteConditionIdSet = new Set<Id>();
        List<Quote> quoteToUpdateList = new List<Quote>();
        Map<Id,MPIntegrationStatus__c> intStatusByMpqcIdMap = new Map<Id,MPIntegrationStatus__c>();
        List<MPQuoteCondition__c> mpqcToUpdateList = new List<MPQuoteCondition__c>();
        
        // Obtener Ids de Condiciones de presupuesto (MPQuoteCondition__c)
        for(MPQuoteCondition__c mpqc : lstMPQuoteCondition){
            quoteConditionIdSet.add(mpqc.Id);
        }

        // Obtener presupuestos (Quote) a actualizar en estado en progreso y organizar en un mapa con los logs
        for(MPQuoteCondition__c mpqc : [SELECT Id, MPQuote__c FROM MPQuoteCondition__c WHERE Id IN :quoteConditionIdSet]){
            quoteToUpdateList.add(new Quote(Id=mpqc.MPQuote__c, MPPricingApiStatus__c = IN_PROGRESS_STATUS));
            if(!intStatusByMpqcIdMap.containsKey(mpqc.Id)){
                MPIntegrationStatus__c newLog = getIntStatus(mpqc.Id);
                intStatusByMpqcIdMap.put(mpqc.Id, newLog);
            }
        }

        // Insertar logs de la integración (MPIntegrationStatus__c)
        if(!intStatusByMpqcIdMap.isEmpty()){
            insert intStatusByMpqcIdMap.values();
        }

        // Actualizar Condiciones de presupuesto (MPQuoteCondition__c)
        for(MPQuoteCondition__c mpqc : lstMPQuoteCondition ){
            MPQuoteCondition__c mpqcTemp = new MPQuoteCondition__c();
            mpqcTemp.Id = mpqc.Id;
            mpqcTemp.MPPricingApiStatus__c = IN_PROGRESS_STATUS;
            if(intStatusByMpqcIdMap.containsKey(mpqcTemp.Id)){
                mpqcTemp.MPIntegrationStatus__c = intStatusByMpqcIdMap.get(mpqcTemp.Id).Id;
            }
            mpqcToUpdateList.add(mpqcTemp);
        }

        if(!mpqcToUpdateList.isEmpty()){
           update mpqcToUpdateList;
        }

        // Actualizar presupuesto (MPQuoteCondition__c)
        if(!quoteToUpdateList.isEmpty()){
            update quoteToUpdateList;
        }

        // Encolar trabajos para ejecutar la integración
        for(MPQuoteCondition__c mpqc : lstMPQuoteCondition ){
            if(intStatusByMpqcIdMap.containsKey(mpqc.Id) && !Test.isRunningTest()){
                PricingAPICallManager callManager = new PricingAPICallManager(mpqc,IS_RETRY_ENABLED,intStatusByMpqcIdMap.get(mpqc.Id));
                System.enqueueJob(new CallManagerQueueable(callManager));
            }
        }
    }

    /**
     * @description Método encargado de crear una nueva instancia del objeto 'MPIntegrationStatus__c'
     * @author Juan Felipe Muriel | 05-08-2024 
     * @param mpqcId Id de una condición de presupuesto (MPQuoteCondition__c)
     * @return Nueva instancia de 'MPIntegrationStatus__c'
     */
    private static MPIntegrationStatus__c getIntStatus(Id mpqcId) {
        MPIntegrationStatus__c newLog = new MPIntegrationStatus__c();
        newLog.MPIntegrationName__c    = INTEGRATION_NAME;
        newLog.MPParentId__c           = String.valueOf(mpqcId);
        newLog.MPStatus__c             = IN_PROGRESS_STATUS;
        return newLog;
    }
}