force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParams__c.field-meta.xml
<CustomField>
    <fullName>MPParams__c</fullName>
    <description>Parametros agregados al cuerpo de la solicitud</description>
    <label>Parámetros</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPInvoice__c/MPInvoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FCT-{00000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPInvoice__c/fields/MPInvoiceAPIStatus__c.field-meta.xml
<CustomField>
    <fullName>MPInvoiceAPIStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles API Create</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceCreateAPI.cls
/**
 * @description       : API para crear facturas recibidas desde SAP.
 * @author            : Luis Sandoval
 * @group             : 
 * @last modified on  : 29-10-2024
 * @last modified by  : Luis Sandoval
**/
@RestResource(urlMapping='/invoices/created')
global class InvoiceCreateAPI { 

    public static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPInvoiceCreate').DeveloperName;
    public static final Integer SUCCESS_HTTP_CODE = Integer.valueOf(Label.MPIntegrationHTTPSuccessCode);

    @HttpPost
    global static void createInvoiceRecord() {

        MPIntegrationStatus__c log = new MPIntegrationStatus__c();
        String invoiceId = null;

        try {
            /* Adding initial log's data */
            log.MPIntegrationName__c    = INTEGRATION_NAME;
            log.MPParams__c             = RestContext.request.requestURI;
            log.MPRequest__c            = RestContext.request.requestBody.toString();
            log.MPRequestDateTime__c    = System.now();
            log.MPStatus__c             = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');

            /* Process the request */
            InvoiceWrapper wrapper = (InvoiceWrapper) JSON.deserialize(RestContext.request.requestBody.toString(), InvoiceWrapper.class);
            String invoiceNumber = wrapper.invoiceNumber;
            wrapper = InvoiceCreateService.validateAndFilterWrapper(wrapper);
            invoiceId = InvoiceCreateService.createInvoiceRecords(wrapper);

        } catch (Exception e) {
            /* Handling errors */
            log.MPSalesforceException__c= Utilities_cls.getSalesforceStackTrace(e);
            log.MPStatus__c             = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
            System.debug(e.getMessage());

        } finally {
            /** Complete log's data */
            log.MPResponseDateTime__c   = System.now();
            log.MPParentId__c           = invoiceId != null ? invoiceId : null;
            log.MPHttpCode__c           = SUCCESS_HTTP_CODE;
            insert log;

            /** Add log to the FTC record*/
            if(invoiceId != null){
               MPInvoice__c invoiceRecord = new MPInvoice__c(Id=invoiceId, MPInvoiceAPIStatus__c = log.Id);
               update invoiceRecord;
            }
            /** Always respond with success http code */ 
            RestContext.response.statusCode = SUCCESS_HTTP_CODE;
        }
    }
}