force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParams__c.field-meta.xml
<CustomField>
    <fullName>MPParams__c</fullName>
    <description>Parametros agregados al cuerpo de la solicitud</description>
    <label>Parámetros</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponse__c.field-meta.xml
<CustomField>
    <fullName>MPResponse__c</fullName>
    <label>Respuesta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractRescissionAPIUtils.cls
/**
 * @description Clase utlitaria de ContractRescissionAPICallManager
 * @group Proyecto MP
 * @author Miller
 * @since 17-10-2024 - Creación
 */
public with sharing class ContractRescissionAPIUtils {
   
    /** Nombre de la integración */
    public static final String INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPContractRescission').DeveloperName;

     /**
    * @description Método el cual modifica los valores del log de integracion antes de hacer UPDATE
    * @author Miller Mora | 20-08-2024 
    * @param callManager Instancia del callManager
    * @return updatedIntStat Registro de log de la transacción actualizado
    **/
    public static MPIntegrationStatus__c modifyIntegrationLog(ContractRescissionAPICallManager callManager){
        MPIntegrationStatus__c updatedIntStat  = callManager.getIntegrationStatus();
        updatedIntStat.MPIntegrationName__c    = INTEGRATION_NAME;
        updatedIntStat.MPParentId__c           = callManager.getParentId();
        updatedIntStat.MPStatus__c             = callManager.contractRescissionAPIWrapper().status;
        updatedIntStat.MPRequest__c            = JSON.serialize(callManager.contractRescissionAPIWrapper().request);
        updatedIntStat.MPRequestDateTime__c    = callManager.contractRescissionAPIWrapper().requestDateTime;
        updatedIntStat.MPResponse__c           = callManager.contractRescissionAPIWrapper().response.message;
        updatedIntStat.MPResponseDateTime__c   = callManager.contractRescissionAPIWrapper().requestDateTime;
        updatedIntStat.MPParams__c             = JSON.serialize(callManager.contractRescissionAPIWrapper().params);
        updatedIntStat.MPSalesforceException__c= callManager.contractRescissionAPIWrapper().salesforceErrorMessage;
        updatedIntStat.MPHttpCode__c           = callManager.contractRescissionAPIWrapper().httpCode;
        System.debug('updatedIntStat' + updatedIntStat);
        return updatedIntStat;
    }

}