force-app/main/default/objects/MPIntegrationStatus__c/MPIntegrationStatus__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena el historico de llamadas a la API de Mall Plaza</description>
    <label>Integration Status</label>
    <nameField>
        <displayFormat>IS-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integrations Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPHttpCode__c.field-meta.xml
<CustomField>
    <fullName>MPHttpCode__c</fullName>
    <label>Código Http</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPIntegrationName__c.field-meta.xml
<CustomField>
    <fullName>MPIntegrationName__c</fullName>
    <description>Nombre de la integración</description>
    <label>Integración</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParams__c.field-meta.xml
<CustomField>
    <fullName>MPParams__c</fullName>
    <description>Parametros agregados al cuerpo de la solicitud</description>
    <label>Parámetros</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPParentId__c.field-meta.xml
<CustomField>
    <fullName>MPParentId__c</fullName>
    <description>Id del registro que desencadena la integración</description>
    <label>Id padre</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequest__c.field-meta.xml
<CustomField>
    <fullName>MPRequest__c</fullName>
    <label>Petición</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPRequestDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPRequestDateTime__c</fullName>
    <label>Fecha de petición</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPResponseDateTime__c.field-meta.xml
<CustomField>
    <fullName>MPResponseDateTime__c</fullName>
    <label>Fecha de respuesta</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPSalesforceException__c.field-meta.xml
<CustomField>
    <fullName>MPSalesforceException__c</fullName>
    <description>Contiene las excepciones capturadas que ocurren en Salesforce</description>
    <label>Error Salesforce</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MPIntegrationStatus__c/fields/MPStatus__c.field-meta.xml
<CustomField>
    <fullName>MPStatus__c</fullName>
    <description>Estado de la integración</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MPIntegrationStatusValues</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MPInvoice__c/MPInvoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>FCT-{00000}</displayFormat>
        <label>Nombre de Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MPInvoice__c/fields/MPInvoicePaidAPIStatus__c.field-meta.xml
<CustomField>
    <fullName>MPInvoicePaidAPIStatus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalles API 24.2</label>
    <referenceTo>MPIntegrationStatus__c</referenceTo>
    <relationshipLabel>Facturas (Detalles API 24.2)</relationshipLabel>
    <relationshipName>Facturas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoicePaidAPI.cls
/**
 * @description Apex class exposed as a REST web service responsible for receiving all invoices 
 * paid from SAP.
 * @group MP Project
 * @author Juan Felipe Muriel
 * @since 10-30-2024 - Creation
 * @TestClass InvoicePaidAPITest
 */
@RestResource(urlMapping='/invoices/paid')
global with sharing class InvoicePaidAPI {
    /** Integration name */
    public static final String  INTEGRATION_NAME = MPIntegrationSetting__mdt.getInstance('MPInvoicePaid').DeveloperName;
    /** Http code to send */
    public static final Integer  SUCCESS_HTTP_CODE = Integer.valueOf(Label.MPInvoicePaidHTTPSuccessCode);

    /**
    * @description Method exposed for POST requests
    * @author Juan Felipe Muriel | 30-10-2024 
    **/
    @HttpPost
    global static void updateInvoice() {

        MPIntegrationStatus__c log = new MPIntegrationStatus__c();
        InvoicePaidService.InvoicePaidWrapper invoiceWrapper = new InvoicePaidService.InvoicePaidWrapper();
        MPInvoice__c invoiceRecord = null;

        try {
            /* Adding initial log's data */
            log.MPIntegrationName__c    = INTEGRATION_NAME;
            log.MPParams__c             = RestContext.request.requestURI;
            log.MPRequest__c            = RestContext.request.requestBody.toString();
            log.MPRequestDateTime__c    = System.now();
            log.MPStatus__c             = Utilities_cls.getSuccessValue('MPIntegrationStatus__c', 'MPStatus__c');

            /* Process the request */
            invoiceWrapper = InvoicePaidService.getWrapper(RestContext.request.requestBody.toString());
            InvoicePaidService.validateWrapper(invoiceWrapper);
            invoiceRecord = InvoicePaidService.getInvoice(invoiceWrapper);
            invoiceRecord = InvoicePaidService.addInvoiceData(invoiceWrapper, invoiceRecord);
            InvoicePaidService.updateInvoice(invoiceRecord);

        } catch (Exception e) {
            /* Error handling */
            log.MPSalesforceException__c= Utilities_cls.getSalesforceStackTrace(e);
            log.MPStatus__c             = Utilities_cls.getErrorValue('MPIntegrationStatus__c', 'MPStatus__c');
            System.debug(e.getMessage());

        } finally {
            /** Completing log values ​​*/
            log.MPResponseDateTime__c   = System.now();
            log.MPParentId__c           = invoiceRecord != null ? invoiceRecord.Id : null;
            log.MPHttpCode__c           = SUCCESS_HTTP_CODE;
            insert log;

            /** Associate the log with the Invoice record */
            if(invoiceRecord != null){
                invoiceRecord.MPInvoicePaidAPIStatus__c = log.Id;
                update invoiceRecord;
            }

            /**
            The client uses a middleware that makes the call to the Salesforce web service, but it cannot handle 
            failures. For this reason:

            1. Even if the integration fails due to business logic, a successful http code will always be responded 
               to the server that makes the call to the web service; however, the log record will indicate the 
               error to the Salesforce administrator.
            2. It is not possible to send a success code during server errors and/or those that cannot be captured 
               from the try catch block
            */            
            RestContext.response.statusCode = SUCCESS_HTTP_CODE;
        }
    }
}